const data = `[{
    "Trophy, Official Ball & Logos": [
      { "id": "0", "name": "Panini Logo" },
      { "id": "1", "name": "FIFA Logo" },
      { "id": "2", "name": "World Cup Trophy" },
      { "id": "3", "name": "2018 World Cup Graphic 1" },
      { "id": "4", "name": "2018 World Cup Graphic 2" },
      { "id": "5", "name": "2018 World Cup Logo 1" },
      { "id": "6", "name": "2018 World Cup Logo 2" },
      { "id": "7", "name": "Official Ball" }
    ],
    "Stadia": [
      { "id": "8", "name": "Ekaterinburg Arena" },
      { "id": "9", "name": "Kaliningrad Stadium" },
      { "id": "10", "name": "Kazan Arena" },
      { "id": "11", "name": "Spartak Stadium" },
      { "id": "12", "name": "Nizhny Novgorod Stadium" },
      { "id": "13", "name": "Luzhniki Stadium" },
      { "id": "14", "name": "Rostov Arena" },
      { "id": "15", "name": "Saint Petersburg Stadium" },
      { "id": "16", "name": "Samara Arena" },
      { "id": "17", "name": "Mordovia Arena" },
      { "id": "18", "name": "Fisht Stadium" },
      { "id": "19", "name": "Volgograd Arena" }
    ],
    "Host cities": [
      { "id": "20", "name": "Moscow 1" },
      { "id": "21", "name": "Moscow 2" },
      { "id": "22", "name": "Kaliningrad" },
      { "id": "23", "name": "Saint Petersburg" },
      { "id": "24", "name": "Sochi" },
      { "id": "25", "name": "Rostov-on-Don" },
      { "id": "26", "name": "Volgograd" },
      { "id": "27", "name": "Kazan" },
      { "id": "28", "name": "Nizhny Novgorod" },
      { "id": "29", "name": "Samara" },
      { "id": "30", "name": "Yekaterinburg" },
      { "id": "31", "name": "Saransk" }
    ],
    "Russia": [
      { "id": "32", "name": "Team Logo - Russia" },
      { "id": "33", "name": "Team Photo - Russia" },
      { "id": "34", "name": "Igor Akinfeev" },
      { "id": "35", "name": "Igor Smolnikov" },
      { "id": "36", "name": "Viktor Vasin" },
      { "id": "37", "name": "Mario Fernandes" },
      { "id": "38", "name": "Fedor Kudryashov" },
      { "id": "39", "name": "Ilya Kutepov" },
      { "id": "40", "name": "Dmitri Kombarov" },
      { "id": "41", "name": "Aleksei Miranchuk" },
      { "id": "42", "name": "Denis Glushakov" },
      { "id": "43", "name": "Aleksandr Golovin" },
      { "id": "44", "name": "Yuri Zhirkov" },
      { "id": "45", "name": "Aleksandr Samedov" },
      { "id": "46", "name": "Aleksandr Erokhin" },
      { "id": "47", "name": "Alan Dzagoev" },
      { "id": "48", "name": "Daler Kuzyayev" },
      { "id": "49", "name": "Dmitry Poloz" },
      { "id": "50", "name": "Fedor Smolov" },
      { "id": "51", "name": "Aleksandr Kokorin" }
    ],
    "Saudi Arabia": [
      { "id": "52", "name": "Team Logo - Saudi Arabia" },
      { "id": "53", "name": "Team Photo - Saudi Arabia" },
      { "id": "54", "name": "Abdullah Al-Mayouf" },
      { "id": "55", "name": "Osama Hawsawi" },
      { "id": "56", "name": "Abdullah Al-Zori" },
      { "id": "57", "name": "Mansoor Al-Harbi" },
      { "id": "58", "name": "Omar Hawsawi" },
      { "id": "59", "name": "Yasser Al-Shahrani" },
      { "id": "60", "name": "Motaz Hawsawi" },
      { "id": "61", "name": "Mohammed Al-Breik" },
      { "id": "62", "name": "Taisir Al-Jassim" },
      { "id": "63", "name": "Salman Al-Faraj" },
      { "id": "64", "name": "Abdulmalek Al-Khaibri" },
      { "id": "65", "name": "Salman Al-Moasher" },
      { "id": "66", "name": "Yahya Al-Shehri" },
      { "id": "67", "name": "Salem Al-Dawsari" },
      { "id": "68", "name": "Nawaf Al-Abed" },
      { "id": "69", "name": "Mohammad Al-Sahlawi" },
      { "id": "70", "name": "Nasser Al-Shamrani" },
      { "id": "71", "name": "Fahad Al-Muwallad" }
    ],
    "Egypt": [
      { "id": "72", "name": "Team Logo - Egypt" },
      { "id": "73", "name": "Team Photo - Egypt" },
      { "id": "74", "name": "Essam El Hadary" },
      { "id": "75", "name": "Ali Gabr" },
      { "id": "76", "name": "Ahmed El Mohamady" },
      { "id": "77", "name": "Omar Gaber" },
      { "id": "78", "name": "Ramy Rabia" },
      { "id": "79", "name": "Ahmed Hegazi" },
      { "id": "80", "name": "Ahmed Abdelmonem Fathy" },
      { "id": "81", "name": "Mohamed Abdel Shafy" },
      { "id": "82", "name": "Saad Samir" },
      { "id": "83", "name": "Tarek Hamed" },
      { "id": "84", "name": "Mahmoud Kahraba" },
      { "id": "85", "name": "Mohamed Elneny" },
      { "id": "86", "name": "Mahmoud Trezeguet" },
      { "id": "87", "name": "Abdallah Said" },
      { "id": "88", "name": "Ramadan Sobhi" },
      { "id": "89", "name": "Ahmed Hassan" },
      { "id": "90", "name": "Mohamed Salah" },
      { "id": "91", "name": "Amr Gamal" }
    ],
    "Uruguay": [
      { "id": "92", "name": "Team Logo - Uruguay" },
      { "id": "93", "name": "Team Photo - Uruguay" },
      { "id": "94", "name": "Fernando Muslera" },
      { "id": "95", "name": "Maxi Pereira" },
      { "id": "96", "name": "Diego Godin" },
      { "id": "97", "name": "Martin Caceres" },
      { "id": "98", "name": "Jose Gimenez" },
      { "id": "99", "name": "Sebastian Coates" },
      { "id": "100", "name": "Gaston Silva" },
      { "id": "101", "name": "Mathias Corujo" },
      { "id": "102", "name": "Egidio Arevalo Rios" },
      { "id": "103", "name": "Alvaro Gonzalez" },
      { "id": "104", "name": "Nicolas Lodeiro" },
      { "id": "105", "name": "Carlos Sanchez" },
      { "id": "106", "name": "Cristian Rodriguez" },
      { "id": "107", "name": "Matias Vecino" },
      { "id": "108", "name": "Edinson Cavani" },
      { "id": "109", "name": "Luis Suarez" },
      { "id": "110", "name": "Cristhian Stuani" },
      { "id": "111", "name": "Diego Rolan" }
    ],
    "Portugal": [
      { "id": "112", "name": "Team Logo - Portugal" },
      { "id": "113", "name": "Team Photo - Portugal" },
      { "id": "114", "name": "RuiPatricio" },
      { "id": "115", "name": "Bruno Alves" },
      { "id": "116", "name": "Pepe" },
      { "id": "117", "name": "Jose Fonte" },
      { "id": "118", "name": "Eliseu" },
      { "id": "119", "name": "Cedric" },
      { "id": "120", "name": "Raphael Guerreiro" },
      { "id": "121", "name": "Joao Moutinho" },
      { "id": "122", "name": "Joao Mario" },
      { "id": "123", "name": "Danilo Pereira" },
      { "id": "124", "name": "William Carvalho" },
      { "id": "125", "name": "Andre Gomes" },
      { "id": "126", "name": "Ricardo Quaresma" },
      { "id": "127", "name": "Bernardo Silva" },
      { "id": "128", "name": "Andre Silva" },
      { "id": "129", "name": "Gelson Martins" },
      { "id": "130", "name": "Cristiano Ronaldo" },
      { "id": "131", "name": "Nani" }
    ],
    "Spain": [
      { "id": "132", "name": "Team Logo - Spain" },
      { "id": "133", "name": "Team Photo - Spain" },
      { "id": "134", "name": "David de Gea" },
      { "id": "135", "name": "Jordi Alba" },
      { "id": "136", "name": "Nacho" },
      { "id": "137", "name": "Nacho Monreal" },
      { "id": "138", "name": "Gerard Pique" },
      { "id": "139", "name": "Sergio Ramos" },
      { "id": "140", "name": "Daniel Carvajal" },
      { "id": "141", "name": "Sergio Busquets" },
      { "id": "142", "name": "Thiago Alcantara" },
      { "id": "143", "name": "Isco" },
      { "id": "144", "name": "Koke" },
      { "id": "145", "name": "Marco Asensio" },
      { "id": "146", "name": "Andres Iniesta" },
      { "id": "147", "name": "David Villa" },
      { "id": "148", "name": "Saul Niguez" },
      { "id": "149", "name": "Alvaro Morata" },
      { "id": "150", "name": "Vitolo" },
      { "id": "151", "name": "Diego Costa" }
    ],
    "Morocco": [
      { "id": "152", "name": "Team Logo - Morocco" },
      { "id": "153", "name": "Team Photo - Morocco" },
      { "id": "154", "name": "Munir Mohamedi" },
      { "id": "155", "name": "Medhi Benatia" },
      { "id": "156", "name": "Nabil Dirar" },
      { "id": "157", "name": "Romain Saiss" },
      { "id": "158", "name": "Fouad Chafik" },
      { "id": "159", "name": "Hamza Mendyl" },
      { "id": "160", "name": "Achraf Hakimi" },
      { "id": "161", "name": "Mbark Boussoufa" },
      { "id": "162", "name": "Karim El Ahmadi" },
      { "id": "163", "name": "Younes Belhanda" },
      { "id": "164", "name": "Nordin Amrabat" },
      { "id": "165", "name": "Faycal Fajr" },
      { "id": "166", "name": "Hakim Ziyech" },
      { "id": "167", "name": "Youssef Ait Bennasser" },
      { "id": "168", "name": "Khalid Boutaib" },
      { "id": "169", "name": "Rachid Alioui" },
      { "id": "170", "name": "Aziz Bouhaddouz" },
      { "id": "171", "name": "Youssef En-Nesyri" }
    ],
    "Iran": [
      { "id": "172", "name": "Team Logo - Iran" },
      { "id": "173", "name": "Team Photo - Iran" },
      { "id": "174", "name": "Alireza Beiranvand" },
      { "id": "175", "name": "Pejman Montazeri" },
      { "id": "176", "name": "Vouria Ghafouri" },
      { "id": "177", "name": "Jalal Hosseini" },
      { "id": "178", "name": "Milad Mohammadi" },
      { "id": "179", "name": "Morteza Pouraliganji" },
      { "id": "180", "name": "Ramin Rezaeian" },
      { "id": "181", "name": "Ehsan Hajsafi" },
      { "id": "182", "name": "Omid Ebrahimi" },
      { "id": "183", "name": "Saeid Ezatolahi" },
      { "id": "184", "name": "Vahid Amiri" },
      { "id": "185", "name": "Alireza Jahanbakhsh" },
      { "id": "186", "name": "Ashkan Dejagah" },
      { "id": "187", "name": "Saman Ghoddos" },
      { "id": "188", "name": "Mehdi Taremi" },
      { "id": "189", "name": "Karim Ansarifard" },
      { "id": "190", "name": "Reza Ghoochannejhad" },
      { "id": "191", "name": "Sardar Azmoun" }
    ],
    "France": [
      { "id": "192", "name": "Team Logo - France" },
      { "id": "193", "name": "Team Photo - France" },
      { "id": "194", "name": "Hugo Lloris" },
      { "id": "195", "name": "Raphael Varane" },
      { "id": "196", "name": "Lucas Digne" },
      { "id": "197", "name": "Djibril Sidibe" },
      { "id": "198", "name": "Samuel Umtiti" },
      { "id": "199", "name": "Layvin Kurzawa" },
      { "id": "200", "name": "Laurent Koscielny" },
      { "id": "201", "name": "Blaise Matuidi" },
      { "id": "202", "name": "N'Golo Kante" },
      { "id": "203", "name": "Thomas Lemar" },
      { "id": "204", "name": "Adrien Rabiot" },
      { "id": "205", "name": "Paul Pogba" },
      { "id": "206", "name": "Olivier Giroud" },
      { "id": "207", "name": "Antoine Griezmann" },
      { "id": "208", "name": "Alexandre Lacazette" },
      { "id": "209", "name": "Kylian Mbappe" },
      { "id": "210", "name": "Ousmane Dembele" },
      { "id": "211", "name": "Anthony Martial" }
    ],
    "Australia": [
      { "id": "212", "name": "TeamLogo - Australia" },
      { "id": "213", "name": "Team Photo - Australia" },
      { "id": "214", "name": "Mathew Ryan" },
      { "id": "215", "name": "Mitchell Langerak" },
      { "id": "216", "name": "Milos Degenek" },
      { "id": "217", "name": "Bailey Wright" },
      { "id": "218", "name": "Aziz Behich" },
      { "id": "219", "name": "Trent Sainsbury" },
      { "id": "220", "name": "Ryan McGowan" },
      { "id": "221", "name": "Mark Milligan" },
      { "id": "222", "name": "Aaron Mooy" },
      { "id": "223", "name": "James Troisi" },
      { "id": "224", "name": "Mile Jedinak" },
      { "id": "225", "name": "Massimo Luongo" },
      { "id": "226", "name": "Jackson Irvine" },
      { "id": "227", "name": "Tom Rogic" },
      { "id": "228", "name": "Tim Cahill" },
      { "id": "229", "name": "Mathew Leckie" },
      { "id": "230", "name": "Tomi Juric" },
      { "id": "231", "name": "Robbie Kruse" }
    ],
    "Peru": [
      { "id": "232", "name": "Team Logo - Peur" },
      { "id": "233", "name": "Team Photo - Peru" },
      { "id": "234", "name": "Pedro Gallese" },
      { "id": "235", "name": "Carlos Caceda" },
      { "id": "236", "name": "Aldo Corzo" },
      { "id": "237", "name": "Miguel Trauco" },
      { "id": "238", "name": "Christian Ramos" },
      { "id": "239", "name": "Luis Advincula" },
      { "id": "240", "name": "Alberto Rodriguez" },
      { "id": "241", "name": "Miguel Araujo" },
      { "id": "242", "name": "Christian Cueva" },
      { "id": "243", "name": "Renato Tapia" },
      { "id": "244", "name": "Andy Polo" },
      { "id": "245", "name": "Yoshimar Yotun" },
      { "id": "246", "name": "Edison Flores" },
      { "id": "247", "name": "Paolo Hurtado" },
      { "id": "248", "name": "Paolo Guerrero" },
      { "id": "249", "name": "Jefferson Farfan" },
      { "id": "250", "name": "Raul Ruidiaz" },
      { "id": "251", "name": "Andre Carrillo" }
    ],
    "Denmark": [
      { "id": "252", "name": "Team Logo - Denmark" },
      { "id": "253", "name": "Team Photo - Denmark" },
      { "id": "254", "name": "Kasper Schmeichel" },
      { "id": "255", "name": "Jannik Vestergaard" },
      { "id": "256", "name": "Simon Kjaer" },
      { "id": "257", "name": "Andreas Christensen" },
      { "id": "258", "name": "Andreas Bjelland" },
      { "id": "259", "name": "Mathias Jorgensen" },
      { "id": "260", "name": "Jens Stryger Larsen" },
      { "id": "261", "name": "Peter Ankersen" },
      { "id": "262", "name": "Riza Durmisi" },
      { "id": "263", "name": "William Kvist" },
      { "id": "264", "name": "Thomas Delaney" },
      { "id": "265", "name": "Christian Eriksen" },
      { "id": "266", "name": "Lasse Schone" },
      { "id": "267", "name": "Pione Sisto" },
      { "id": "268", "name": "Nicklas Bendtner" },
      { "id": "269", "name": "Nicolai Jorgensen" },
      { "id": "270", "name": "Yussuf Poulsen" },
      { "id": "271", "name": "Andreas Cornelius" }
    ],
    "Argentina": [
      { "id": "272", "name": "Team Logo - Argentina" },
      { "id": "273", "name": "Team Photo - Argentina" },
      { "id": "274", "name": "Sergio Romero" },
      { "id": "275", "name": "Gabriel Mercado" },
      { "id": "276", "name": "Federico Fazio" },
      { "id": "277", "name": "Javier Mascherano" },
      { "id": "278", "name": "Nicolas Otamendi" },
      { "id": "279", "name": "Marcos Rojo" },
      { "id": "280", "name": "Ramiro Funes Mori" },
      { "id": "281", "name": "Lucas Biglia" },
      { "id": "282", "name": "Enzo Perez" },
      { "id": "283", "name": "Angel Di Maria" },
      { "id": "284", "name": "Marcos Acuna" },
      { "id": "285", "name": "Ever Banega" },
      { "id": "286", "name": "Eduardo Salvio" },
      { "id": "287", "name": "Mauro Icardi" },
      { "id": "288", "name": "Lionel Messi" },
      { "id": "289", "name": "PauloDybala" },
      { "id": "290", "name": "Sergio Aguero" },
      { "id": "291", "name": "Gonzalo Higuain" }
    ],
    "Iceland": [
      { "id": "292", "name": "Team Logo - Iceland" },
      { "id": "293", "name": "Team Photo - Iceland" },
      { "id": "294", "name": "Hannes Halldorsson" },
      { "id": "295", "name": "Birkir Saevarsson" },
      { "id": "296", "name": "Ragnar Sigurosson" },
      { "id": "297", "name": "Kari Arnason" },
      { "id": "298", "name": "Ari Skulason" },
      { "id": "299", "name": "Sverrir Ingason" },
      { "id": "300", "name": "Hordur Magnusson" },
      { "id": "301", "name": "Aron Gunnarsson" },
      { "id": "302", "name": "Birkir Bjarnason" },
      { "id": "303", "name": "Emil Hallfredsson" },
      { "id": "304", "name": "Gylfi Sigurdsson" },
      { "id": "305", "name": "Arnor Ingvi Traustason" },
      { "id": "306", "name": "Rurik Gislason" },
      { "id": "307", "name": "Johann Gudmundsson" },
      { "id": "308", "name": "Alfred Finnbogason" },
      { "id": "309", "name": "Jon Dadi Bodvarsson" },
      { "id": "310", "name": "Vidar Orn Kjartansson" },
      { "id": "311", "name": "Bjorn Sigurdarson" }
    ],
    "Croatia": [
      { "id": "312", "name": "Team Logo - Croatia" },
      { "id": "313", "name": "Team Photo - Croatia" },
      { "id": "314", "name": "Danijel Subasic" },
      { "id": "315", "name": "Sime Vrsaljko" },
      { "id": "316", "name": "Ivan Strinic" },
      { "id": "317", "name": "Dejan Lovren" },
      { "id": "318", "name": "Domagoj Vida" },
      { "id": "319", "name": "Josip Pivaric" },
      { "id": "320", "name": "Vedran Corluka" },
      { "id": "321", "name": "Ivan Rakitic" },
      { "id": "322", "name": "Luka Modric" },
      { "id": "323", "name": "Marcelo Brozovic" },
      { "id": "324", "name": "Marko Rog" },
      { "id": "325", "name": "Mario Pasalic" },
      { "id": "326", "name": "Milan Badelj" },
      { "id": "327", "name": "Mateo Kovacic" },
      { "id": "328", "name": "Andrej Kramaric" },
      { "id": "329", "name": "Nikola Kalinic" },
      { "id": "330", "name": "Mario Mandzukic" },
      { "id": "331", "name": "Ivan Perisic" }
    ],
    "Nigeria": [
      { "id": "332", "name": "Team Logo - Nigeria" },
      { "id": "333", "name": "Team Photo - Nigeria" },
      { "id": "334", "name": "Ikechukwu Ezenwa" },
      { "id": "335", "name": "Elderson Echiejile" },
      { "id": "336", "name": "Shehu Abdullahi" },
      { "id": "337", "name": "William Troost-Ekong" },
      { "id": "338", "name": "Leon Balogun" },
      { "id": "339", "name": "Kenneth Omeruo" },
      { "id": "340", "name": "Ola Aina" },
      { "id": "341", "name": "John Obi Mikel" },
      { "id": "342", "name": "Ogenyi Onazi" },
      { "id": "343", "name": "Etebo Oghenekaro" },
      { "id": "344", "name": "Wilfred Ndidi" },
      { "id": "345", "name": "Mikel Agu" },
      { "id": "346", "name": "Ahmed Musa" },
      { "id": "347", "name": "Victor Moses" },
      { "id": "348", "name": "Moses Simon" },
      { "id": "349", "name": "Odion Ighalo" },
      { "id": "350", "name": "Alex Iwobi" },
      { "id": "351", "name": "Kelechi Iheanacho" }
    ],
    "Brazil": [
      { "id": "352", "name": "Team Logo - Brazil" },
      { "id": "353", "name": "TeamPhoto - Brazil" },
      { "id": "354", "name": "Alisson" },
      { "id": "355", "name": "Dani Alves" },
      { "id": "356", "name": "Thiago Silva" },
      { "id": "357", "name": "Miranda" },
      { "id": "358", "name": "Filipe Luis" },
      { "id": "359", "name": "Marquinhos" },
      { "id": "360", "name": "Marcelo" },
      { "id": "361", "name": "Willian" },
      { "id": "362", "name": "Paulinho" },
      { "id": "363", "name": "Fernandinho" },
      { "id": "364", "name": "Casemiro" },
      { "id": "365", "name": "Renato Augusto" },
      { "id": "366", "name": "Giuliano" },
      { "id": "367", "name": "Philippe Coutinho" },
      { "id": "368", "name": "Douglas Costa" },
      { "id": "369", "name": "Roberto Firmino" },
      { "id": "370", "name": "Gabriel Jesus" },
      { "id": "371", "name": "Neymar Jr" }
    ],
    "Switzerland": [
      { "id": "372", "name": "Team Logo - Switzerland" },
      { "id": "373", "name": "Team Photo - Switzerland" },
      { "id": "374", "name": "Yann Sommer" },
      { "id": "375", "name": "Stephan Lichtsteiner" },
      { "id": "376", "name": "Manuel Akanji" },
      { "id": "377", "name": "Michael Lang" },
      { "id": "378", "name": "Ricardo Rodriguez" },
      { "id": "379", "name": "Johan Djourou" },
      { "id": "380", "name": "Fabian Schar" },
      { "id": "381", "name": "Granit Xhaka" },
      { "id": "382", "name": "Steven Zuber" },
      { "id": "383", "name": "Blerim Dzemaili" },
      { "id": "384", "name": "Denis Zakaria" },
      { "id": "385", "name": "Xherdan Shaqiri" },
      { "id": "386", "name": "Valon Behrami" },
      { "id": "387", "name": "Gelson Fernandes" },
      { "id": "388", "name": "Breel Embolo" },
      { "id": "389", "name": "Haris Seferovic" },
      { "id": "390", "name": "Admir Mehmedi" },
      { "id": "391", "name": "Eren Derdiyok" }
    ],
    "Costa Rica": [
      { "id": "392", "name": "Team Logo - Costa Rica" },
      { "id": "393", "name": "Team Photo - Costa Rica" },
      { "id": "394", "name": "Keylor Navas" },
      { "id": "395", "name": "Giancarlo Gonzalez" },
      { "id": "396", "name": "Cristian Gamboa" },
      { "id": "397", "name": "Bryan Oviedo" },
      { "id": "398", "name": "Francisco Calvo" },
      { "id": "399", "name": "Kendall Waston" },
      { "id": "400", "name": "Ronald Matarrita" },
      { "id": "401", "name": "Michael Umana" },
      { "id": "402", "name": "Johnny Acosta" },
      { "id": "403", "name": "Bryan Ruiz" },
      { "id": "404", "name": "Celso Borges" },
      { "id": "405", "name": "Christian Bolanos" },
      { "id": "406", "name": "Randall Azofeifa" },
      { "id": "407", "name": "David Guzman" },
      { "id": "408", "name": "Rodney Wallace" },
      { "id": "409", "name": "Joel Campbell" },
      { "id": "410", "name": "Marco Urena" },
      { "id": "411", "name": "Johan Venegas" }
    ],
    "Serbia": [
      { "id": "412", "name": "Team Logo - Serbia" },
      { "id": "413", "name": "Team Photo - Serbia" },
      { "id": "414", "name": "Vladimir Stojkovic" },
      { "id": "415", "name": "Branislav Ivanovic" },
      { "id": "416", "name": "Aleksandar Kolarov" },
      { "id": "417", "name": "Antonio Rukavina" },
      { "id": "418", "name": "Matija Nastasic" },
      { "id": "419", "name": "Dusko Tosic" },
      { "id": "420", "name": "Nikola Maksimovic" },
      { "id": "421", "name": "Jagos Vukovic" },
      { "id": "422", "name": "Dusan Tadic" },
      { "id": "423", "name": "Sergej Milinkovic-Savic" },
      { "id": "424", "name": "Nemanja Matic" },
      { "id": "425", "name": "Luka Milivojevic" },
      { "id": "426", "name": "Adem Ljajic" },
      { "id": "427", "name": "Nemanja Gudelj" },
      { "id": "428", "name": "Mijat Gacinovic" },
      { "id": "429", "name": "Filip Kostic" },
      { "id": "430", "name": "Aleksandar Mitrovic" },
      { "id": "431", "name": "Aleksandar Prijovic" }
    ],
    "Germany": [
      { "id": "432", "name": "Team Logo - Germany" },
      { "id": "433", "name": "Team Photo - Germany" },
      { "id": "434", "name": "Manuel Neuer" },
      { "id": "435", "name": "Mats Hummels" },
      { "id": "436", "name": "Antonio Rudiger" },
      { "id": "437", "name": "Jerome Boateng" },
      { "id": "438", "name": "Joshua Kimmich" },
      { "id": "439", "name": "Jonas Hector" },
      { "id": "440", "name": "Julian Draxler" },
      { "id": "441", "name": "Toni Kroos" },
      { "id": "442", "name": "Emre Can" },
      { "id": "443", "name": "Leon Goretzka" },
      { "id": "444", "name": "Julian Brandt" },
      { "id": "445", "name": "Sebastian Rudy" },
      { "id": "446", "name": "Leroy Sane" },
      { "id": "447", "name": "Mesut Ozil" },
      { "id": "448", "name": "Sami Khedira" },
      { "id": "449", "name": "Mario Gotze" },
      { "id": "450", "name": "Thomas Muller" },
      { "id": "451", "name": "Timo Werner" }
    ],
    "Mexico": [
      { "id": "452", "name": "Team Logo - Mexico" },
      { "id": "453", "name": "Team Photo - Mexico" },
      { "id": "454", "name": "Guillermo Ochoa" },
      { "id": "455", "name": "Hugo Ayala" },
      { "id": "456", "name": "Diego Reyes" },
      { "id": "457", "name": "Hector Moreno" },
      { "id": "458", "name": "Jesus Gallardo" },
      { "id": "459", "name": "Miguel Layun" },
      { "id": "460", "name": "Carlos Salcedo" },
      { "id": "461", "name": "Jonathan dos Santos" },
      { "id": "462", "name": "Giovani dos Santos" },
      { "id": "463", "name": "Andres Guardado" },
      { "id": "464", "name": "Hector Herrera" },
      { "id": "465", "name": "Javier Aquino" },
      { "id": "466", "name": "Jesus Corona" },
      { "id": "467", "name": "Hirving Lozano" },
      { "id": "468", "name": "Raul Jimenez" },
      { "id": "469", "name": "Carlos Vela" },
      { "id": "470", "name": "Javier Hernandez" },
      { "id": "471", "name": "Oribe Peralta" }
    ],
    "Sweden": [
      { "id": "472", "name": "Team Logo - Sweden" },
      { "id": "473", "name": "Team Photo - Sweden" },
      { "id": "474", "name": "Robin Olsen" },
      { "id": "475", "name": "Mikael Lustig" },
      { "id": "476", "name": "Victor Nilsson Lindelof" },
      { "id": "478", "name": "Andreas Granqvist" },
      { "id": "478", "name": "Martin Olsson" },
      { "id": "479", "name": "Ludwig Augustinsson" },
      { "id": "480", "name": "Emil Krafth" },
      { "id": "481", "name": "Pontus Jansson" },
      { "id": "482", "name": "Sebastian Larsson" },
      { "id": "483", "name": "Emil Forsberg" },
      { "id": "484", "name": "Gustav Svensson" },
      { "id": "485", "name": "Viktor Claesson" },
      { "id": "486", "name": "Jimmy Durmaz" },
      { "id": "487", "name": "Albin Ekdal" },
      { "id": "488", "name": "Isaac Kiese Thelin" },
      { "id": "489", "name": "Marcus Berg" },
      { "id": "490", "name": "John Guidetti" },
      { "id": "491", "name": "Ola Toivonen" }
    ],
    "South Korea": [
      { "id": "492", "name": "Team Logo - South Korea" },
      { "id": "493", "name": "Team Photo - South Korea" },
      { "id": "494", "name": "Kim Seung-gyu" },
      { "id": "495", "name": "Kim Young-gwon" },
      { "id": "496", "name": "Kim Jin-su" },
      { "id": "497", "name": "Kwak Tae-hwi" },
      { "id": "498", "name": "Hong Jeong-ho" },
      { "id": "499", "name": "Jang Hyun-soo" },
      { "id": "500", "name": "Koo Ja-cheol" },
      { "id": "501", "name": "Kwon Chang-hoon" },
      { "id": "502", "name": "Ki Sung-yueng" },
      { "id": "503", "name": "Nam Tae-hee" },
      { "id": "504", "name": "Han Kook-young" },
      { "id": "505", "name": "Lee Chung-yong" },
      { "id": "506", "name": "Jung Woo-young" },
      { "id": "507", "name": "Lee Jae-sung" },
      { "id": "508", "name": "Son Heung-min" },
      { "id": "509", "name": "Ji Dong-won" },
      { "id": "510", "name": "Kim Shin-wook" },
      { "id": "511", "name": "Hwang Hee-chan" }
    ],
    "Belgium": [
      { "id": "512", "name": "Team Logo - Belgium" },
      { "id": "513", "name": "Team Photo - Belgium" },
      { "id": "514", "name": "Thibaut Courtois" },
      { "id": "515", "name": "Toby Alderweireld" },
      { "id": "516", "name": "Thomas Vermaelen" },
      { "id": "517", "name": "Jan Vertonghen" },
      { "id": "518", "name": "Vincent Kompany" },
      { "id": "519", "name": "Thomas Meunier" },
      { "id": "520", "name": "Axel Witsel" },
      { "id": "521", "name": "Radja Nainggolan" },
      { "id": "522", "name": "Kevin De Bruyne" },
      { "id": "523", "name": "Marouane Fellaini" },
      { "id": "524", "name": "Youri Tielemans" },
      { "id": "525", "name": "Mousa Dembele" },
      { "id": "526", "name": "Nacer Chadli" },
      { "id": "527", "name": "Eden Hazard" },
      { "id": "528", "name": "Yannick Carrasco" },
      { "id": "529", "name": "Dries Mertens" },
      { "id": "530", "name": "Michy Batshuayi" },
      { "id": "531", "name": "Romelu Lukaku" }
    ],
    "Panama": [
      { "id": "532", "name": "Team Logo - Panama" },
      { "id": "533", "name": "Team Photo - Panama" },
      { "id": "534", "name": "Jaime Penedo" },
      { "id": "535", "name": "Jose Calderon" },
      { "id": "536", "name": "Michael Murillo" },
      { "id": "537", "name": "Fidel Escobar" },
      { "id": "538", "name": "Roman Torres" },
      { "id": "539", "name": "Adolfo Machado" },
      { "id": "540", "name": "Eric Davis" },
      { "id": "541", "name": "Luis Ovalle" },
      { "id": "542", "name": "Felipe Baloy" },
      { "id": "543", "name": "Gabriel Gomez" },
      { "id": "544", "name": "Edgar Barcenas" },
      { "id": "545", "name": "Armando Cooper" },
      { "id": "546", "name": "Alberto Quintero" },
      { "id": "547", "name": "Anibal Godoy" },
      { "id": "548", "name": "Blas Perez" },
      { "id": "549", "name": "Gabriel Torres" },
      { "id": "550", "name": "Luis Tejada" },
      { "id": "551", "name": "Abdiel Arroyo" }
    ],
    "Tunisia": [
      { "id": "552", "name": "Team Logo - Tunisia" },
      { "id": "553", "name": "Team Photo - Tunisia" },
      { "id": "554", "name": "Aymen Mathlouthi" },
      { "id": "555", "name": "Ali Maaloul" },
      { "id": "556", "name": "Syam Ben Youssef" },
      { "id": "557", "name": "Aymen Abdennour" },
      { "id": "558", "name": "Hamdi Nagguez" },
      { "id": "559", "name": "Yassine Meriah" },
      { "id": "560", "name": "Oussama Haddadi" },
      { "id": "561", "name": "Ferjani Sassi" },
      { "id": "562", "name": "Wahbi Khazri" },
      { "id": "563", "name": "Mohamed Amine Ben Amor" },
      { "id": "564", "name": "Ghailene Chaalali" },
      { "id": "565", "name": "Naim Sliti" },
      { "id": "566", "name": "Youssef Msakni" },
      { "id": "567", "name": "Fakhreddine Ben Youssef" },
      { "id": "568", "name": "Taha Yassine Khenissi" },
      { "id": "569", "name": "Yoann Touzghar" },
      { "id": "570", "name": "Anice Badri" },
      { "id": "571", "name": "Ahmed Akaichi" }
    ],
    "England": [
      { "id": "572", "name": "Team Logo - England" },
      { "id": "573", "name": "Team Photo - England" },
      { "id": "574", "name": "Joe Hart" },
      { "id": "575", "name": "Jordan Pickford" },
      { "id": "576", "name": "Gary Cahill" },
      { "id": "577", "name": "Kyle Walker" },
      { "id": "578", "name": "John Stones" },
      { "id": "579", "name": "Ryan Bertrand" },
      { "id": "580", "name": "Danny Rose" },
      { "id": "581", "name": "Phil Jones" },
      { "id": "582", "name": "Jordan Henderson" },
      { "id": "583", "name": "Alex Oxlade-Chamberlain" },
      { "id": "584", "name": "Dele Alli" },
      { "id": "585", "name": "Eric Dier" },
      { "id": "586", "name": "Adam Lallana" },
      { "id": "587", "name": "Jesse Lingard" },
      { "id": "588", "name": "Raheem Sterling" },
      { "id": "589", "name": "Harry Kane" },
      { "id": "590", "name": "Marcus Rashford" },
      { "id": "591", "name": "Jamie Vardy" }
    ],
    "Poland": [
      { "id": "592", "name": "Team Logo - Poland" },
      { "id": "593", "name": "Team Photo - Poland" },
      { "id": "594", "name": "Lukasz Fabianski" },
      { "id": "595", "name": "Wojciech Szczesny" },
      { "id": "596", "name": "Lukasz Piszczek" },
      { "id": "597", "name": "Kamil Glik" },
      { "id": "598", "name": "Michal Pazdan" },
      { "id": "599", "name": "Thiago Cionek" },
      { "id": "600", "name": "Bartosz Bereszynski" },
      { "id": "601", "name": "Artur Jedrzejczyk" },
      { "id": "602", "name": "Maciej Rybus" },
      { "id": "603", "name": "Jakub Blaszczykowski" },
      { "id": "604", "name": "Kamil Grosicki" },
      { "id": "605", "name": "Grzegorz Krychowiak" },
      { "id": "606", "name": "Krzysztof Maczynski" },
      { "id": "607", "name": "Piotr Zielinski" },
      { "id": "608", "name": "Karol Linetty" },
      { "id": "609", "name": "Robert Lewandowski" },
      { "id": "610", "name": "Lukasz Teodorczyk" },
      { "id": "611", "name": "Arkadiusz Milik" }
    ],
    "Senegal": [
      { "id": "612", "name": "Team Logo - Senegal" },
      { "id": "613", "name": "Team Photo - Senegal" },
      { "id": "614", "name": "Khadim N'Diaye" },
      { "id": "615", "name": "Kara Mbodji" },
      { "id": "616", "name": "Lamine Gassama" },
      { "id": "617", "name": "Kalidou Koulibaly" },
      { "id": "618", "name": "Salif Sane" },
      { "id": "619", "name": "Saliou Ciss" },
      { "id": "620", "name": "Moussa Wague" },
      { "id": "621", "name": "Idrissa Gueye" },
      { "id": "622", "name": "Cheikhou Kouyate" },
      { "id": "623", "name": "Cheikh Ndoye" },
      { "id": "624", "name": "Pape Alioune N'Diaye" },
      { "id": "625", "name": "Sadio Mane" },
      { "id": "626", "name": "Moussa Sow" },
      { "id": "627", "name": "Moussa Konate" },
      { "id": "628", "name": "Keita Balde" },
      { "id": "629", "name": "M'Baye Niang" },
      { "id": "630", "name": "Ismaila Sarr" },
      { "id": "631", "name": "Mame Diouf" }
    ]
  }]`;

const groupData = JSON.parse(data)[0];

for (let group in groupData) {
    groupData[group].forEach(item => {
        item['has'] = Math.floor(Math.random() * (10 - 0) + 0);
    });
}

console.log(JSON.stringify(groupData));