const rawData = `[
    {
      "Trophy, Official Ball & Logos": "0 Panini Logo",
      "Stadia": "8 Ekaterinburg Arena",
      "Host cities": "20 Moscow 1",
      "Russia": "32 Team Logo - Russia",
      "Saudi Arabia": "52 Team Logo - Saudi Arabia",
      "Egypt": "72 Team Logo - Egypt",
      "Uruguay": "92 Team Logo - Uruguay",
      "Portugal": "112 Team Logo - Portugal",
      "Spain": "132 Team Logo - Spain",
      "Morocco": "152 Team Logo - Morocco",
      "Iran": "172 Team Logo - Iran",
      "France": "192 Team Logo - France",
      "Australia": "212 Team Logo - Australia",
      "Peru": "232 Team Logo - Peur",
      "Denmark": "252 Team Logo - Denmark",
      "Argentina": "272 Team Logo - Argentina",
      "Iceland": "292 Team Logo - Iceland",
      "Croatia": "312 Team Logo - Croatia",
      "Nigeria": "332 Team Logo - Nigeria",
      "Brazil": "352 Team Logo - Brazil",
      "Switzerland": "372 Team Logo - Switzerland",
      "Costa Rica": "392 Team Logo - Costa Rica",
      "Serbia": "412 Team Logo - Serbia",
      "Germany": "432 Team Logo - Germany",
      "Mexico": "452 Team Logo - Mexico",
      "Sweden": "472 Team Logo - Sweden",
      "South Korea": "492 Team Logo - South Korea",
      "Belgium": "512 Team Logo - Belgium",
      "Panama": "532 Team Logo - Panama",
      "Tunisia": "552 Team Logo - Tunisia",
      "England": "572 Team Logo - England",
      "Poland": "592 Team Logo - Poland",
      "Senegal": "612 Team Logo - Senegal"
    },
    {
      "Trophy, Official Ball & Logos": "1 FIFA Logo",
      "Stadia": "9 Kaliningrad Stadium",
      "Host cities": "21 Moscow 2",
      "Russia": "33 Team Photo - Russia",
      "Saudi Arabia": "53 Team Photo - Saudi Arabia",
      "Egypt": "73 Team Photo - Egypt",
      "Uruguay": "93 Team Photo - Uruguay",
      "Portugal": "113 Team Photo - Portugal",
      "Spain": "133 Team Photo - Spain",
      "Morocco": "153 Team Photo - Morocco",
      "Iran": "173 Team Photo - Iran",
      "France": "193 Team Photo - France",
      "Australia": "213 Team Photo - Australia",
      "Peru": "233 Team Photo - Peru",
      "Denmark": "253 Team Photo - Denmark",
      "Argentina": "273 Team Photo - Argentina",
      "Iceland": "293 Team Photo - Iceland",
      "Croatia": "313 Team Photo - Croatia",
      "Nigeria": "333 Team Photo - Nigeria",
      "Brazil": "353 Team Photo - Brazil",
      "Switzerland": "373 Team Photo - Switzerland",
      "Costa Rica": "393 Team Photo - Costa Rica",
      "Serbia": "413 Team Photo - Serbia",
      "Germany": "433 Team Photo - Germany",
      "Mexico": "453 Team Photo - Mexico",
      "Sweden": "473 Team Photo - Sweden",
      "South Korea": "493 Team Photo - South Korea",
      "Belgium": "513 Team Photo - Belgium",
      "Panama": "533 Team Photo - Panama",
      "Tunisia": "553 Team Photo - Tunisia",
      "England": "573 Team Photo - England",
      "Poland": "593 Team Photo - Poland",
      "Senegal": "613 Team Photo - Senegal"
    },
    {
      "Trophy, Official Ball & Logos": "2 World Cup Trophy",
      "Stadia": "10 Kazan Arena",
      "Host cities": "22 Kaliningrad",
      "Russia": "34 Igor Akinfeev",
      "Saudi Arabia": "54 Abdullah Al-Mayouf",
      "Egypt": "74 Essam El Hadary",
      "Uruguay": "94 Fernando Muslera",
      "Portugal": "114 Rui Patricio",
      "Spain": "134 David de Gea",
      "Morocco": "154 Munir Mohamedi",
      "Iran": "174 Alireza Beiranvand",
      "France": "194 Hugo Lloris",
      "Australia": "214 Mathew Ryan",
      "Peru": "234 Pedro Gallese",
      "Denmark": "254 Kasper Schmeichel",
      "Argentina": "274 Sergio Romero",
      "Iceland": "294 Hannes Halldorsson",
      "Croatia": "314 Danijel Subasic",
      "Nigeria": "334 Ikechukwu Ezenwa",
      "Brazil": "354 Alisson",
      "Switzerland": "374 Yann Sommer",
      "Costa Rica": "394 Keylor Navas",
      "Serbia": "414 Vladimir Stojkovic",
      "Germany": "434 Manuel Neuer",
      "Mexico": "454 Guillermo Ochoa",
      "Sweden": "474 Robin Olsen",
      "South Korea": "494 Kim Seung-gyu",
      "Belgium": "514 Thibaut Courtois",
      "Panama": "534 Jaime Penedo",
      "Tunisia": "554 Aymen Mathlouthi",
      "England": "574 Joe Hart",
      "Poland": "594 Lukasz Fabianski",
      "Senegal": "614 Khadim N'Diaye"
    },
    {
      "Trophy, Official Ball & Logos": "3 2018 World Cup Graphic 1",
      "Stadia": "11 Spartak Stadium",
      "Host cities": "23 Saint Petersburg",
      "Russia": "35 Igor Smolnikov",
      "Saudi Arabia": "55 Osama Hawsawi",
      "Egypt": "75 Ali Gabr",
      "Uruguay": "95 Maxi Pereira",
      "Portugal": "115 Bruno Alves",
      "Spain": "135 Jordi Alba",
      "Morocco": "155 Medhi Benatia",
      "Iran": "175 Pejman Montazeri",
      "France": "195 Raphael Varane",
      "Australia": "215 Mitchell Langerak",
      "Peru": "235 Carlos Caceda",
      "Denmark": "255 Jannik Vestergaard",
      "Argentina": "275 Gabriel Mercado",
      "Iceland": "295 Birkir Saevarsson",
      "Croatia": "315 Sime Vrsaljko",
      "Nigeria": "335 Elderson Echiejile",
      "Brazil": "355 Dani Alves",
      "Switzerland": "375 Stephan Lichtsteiner",
      "Costa Rica": "395 Giancarlo Gonzalez",
      "Serbia": "415 Branislav Ivanovic",
      "Germany": "435 Mats Hummels",
      "Mexico": "455 Hugo Ayala",
      "Sweden": "475 Mikael Lustig",
      "South Korea": "495 Kim Young-gwon",
      "Belgium": "515 Toby Alderweireld",
      "Panama": "535 Jose Calderon",
      "Tunisia": "555 Ali Maaloul",
      "England": "575 Jordan Pickford",
      "Poland": "595 Wojciech Szczesny",
      "Senegal": "615 Kara Mbodji"
    },
    {
      "Trophy, Official Ball & Logos": "4 2018 World Cup Graphic 2",
      "Stadia": "12 Nizhny Novgorod Stadium",
      "Host cities": "24 Sochi",
      "Russia": "36 Viktor Vasin",
      "Saudi Arabia": "56 Abdullah Al-Zori",
      "Egypt": "76 Ahmed El Mohamady",
      "Uruguay": "96 Diego Godin",
      "Portugal": "116 Pepe",
      "Spain": "136 Nacho",
      "Morocco": "156 Nabil Dirar",
      "Iran": "176 Vouria Ghafouri",
      "France": "196 Lucas Digne",
      "Australia": "216 Milos Degenek",
      "Peru": "236 Aldo Corzo",
      "Denmark": "256 Simon Kjaer",
      "Argentina": "276 Federico Fazio",
      "Iceland": "296 Ragnar Sigurosson",
      "Croatia": "316 Ivan Strinic",
      "Nigeria": "336 Shehu Abdullahi",
      "Brazil": "356 Thiago Silva",
      "Switzerland": "376 Manuel Akanji",
      "Costa Rica": "396 Cristian Gamboa",
      "Serbia": "416 Aleksandar Kolarov",
      "Germany": "436 Antonio Rudiger",
      "Mexico": "456 Diego Reyes",
      "Sweden": "476 Victor Nilsson Lindelof",
      "South Korea": "496 Kim Jin-su",
      "Belgium": "516 Thomas Vermaelen",
      "Panama": "536 Michael Murillo",
      "Tunisia": "556 Syam Ben Youssef",
      "England": "576 Gary Cahill",
      "Poland": "596 Lukasz Piszczek",
      "Senegal": "616 Lamine Gassama"
    },
    {
      "Trophy, Official Ball & Logos": "5 2018 World Cup Logo 1",
      "Stadia": "13 Luzhniki Stadium",
      "Host cities": "25 Rostov-on-Don",
      "Russia": "37 Mario Fernandes",
      "Saudi Arabia": "57 Mansoor Al-Harbi",
      "Egypt": "77 Omar Gaber",
      "Uruguay": "97 Martin Caceres",
      "Portugal": "117 Jose Fonte",
      "Spain": "137 Nacho Monreal",
      "Morocco": "157 Romain Saiss",
      "Iran": "177 Jalal Hosseini",
      "France": "197 Djibril Sidibe",
      "Australia": "217 Bailey Wright",
      "Peru": "237 Miguel Trauco",
      "Denmark": "257 Andreas Christensen",
      "Argentina": "277 Javier Mascherano",
      "Iceland": "297 Kari Arnason",
      "Croatia": "317 Dejan Lovren",
      "Nigeria": "337 William Troost-Ekong",
      "Brazil": "357 Miranda",
      "Switzerland": "377 Michael Lang",
      "Costa Rica": "397 Bryan Oviedo",
      "Serbia": "417 Antonio Rukavina",
      "Germany": "437 Jerome Boateng",
      "Mexico": "457 Hector Moreno",
      "Sweden": "478 Andreas Granqvist",
      "South Korea": "497 Kwak Tae-hwi",
      "Belgium": "517 Jan Vertonghen",
      "Panama": "537 Fidel Escobar",
      "Tunisia": "557 Aymen Abdennour",
      "England": "577 Kyle Walker",
      "Poland": "597 Kamil Glik",
      "Senegal": "617 Kalidou Koulibaly"
    },
    {
      "Trophy, Official Ball & Logos": "6 2018 World Cup Logo 2",
      "Stadia": "14 Rostov Arena",
      "Host cities": "26 Volgograd",
      "Russia": "38 Fedor Kudryashov",
      "Saudi Arabia": "58 Omar Hawsawi",
      "Egypt": "78 Ramy Rabia",
      "Uruguay": "98 Jose Gimenez",
      "Portugal": "118 Eliseu",
      "Spain": "138 Gerard Pique",
      "Morocco": "158 Fouad Chafik",
      "Iran": "178 Milad Mohammadi",
      "France": "198 Samuel Umtiti",
      "Australia": "218 Aziz Behich",
      "Peru": "238 Christian Ramos",
      "Denmark": "258 Andreas Bjelland",
      "Argentina": "278 Nicolas Otamendi",
      "Iceland": "298 Ari Skulason",
      "Croatia": "318 Domagoj Vida",
      "Nigeria": "338 Leon Balogun",
      "Brazil": "358 Filipe Luis",
      "Switzerland": "378 Ricardo Rodriguez",
      "Costa Rica": "398 Francisco Calvo",
      "Serbia": "418 Matija Nastasic",
      "Germany": "438 Joshua Kimmich",
      "Mexico": "458 Jesus Gallardo",
      "Sweden": "478 Martin Olsson",
      "South Korea": "498 Hong Jeong-ho",
      "Belgium": "518 Vincent Kompany",
      "Panama": "538 Roman Torres",
      "Tunisia": "558 Hamdi Nagguez",
      "England": "578 John Stones",
      "Poland": "598 Michal Pazdan",
      "Senegal": "618 Salif Sane"
    },
    {
      "Trophy, Official Ball & Logos": "7 Official Ball",
      "Stadia": "15 Saint Petersburg Stadium",
      "Host cities": "27 Kazan",
      "Russia": "39 Ilya Kutepov",
      "Saudi Arabia": "59 Yasser Al-Shahrani",
      "Egypt": "79 Ahmed Hegazi",
      "Uruguay": "99 Sebastian Coates",
      "Portugal": "119 Cedric",
      "Spain": "139 Sergio Ramos",
      "Morocco": "159 Hamza Mendyl",
      "Iran": "179 Morteza Pouraliganji",
      "France": "199 Layvin Kurzawa",
      "Australia": "219 Trent Sainsbury",
      "Peru": "239 Luis Advincula",
      "Denmark": "259 Mathias Jorgensen",
      "Argentina": "279 Marcos Rojo",
      "Iceland": "299 Sverrir Ingason",
      "Croatia": "319 Josip Pivaric",
      "Nigeria": "339 Kenneth Omeruo",
      "Brazil": "359 Marquinhos",
      "Switzerland": "379 Johan Djourou",
      "Costa Rica": "399 Kendall Waston",
      "Serbia": "419 Dusko Tosic",
      "Germany": "439 Jonas Hector",
      "Mexico": "459 Miguel Layun",
      "Sweden": "479 Ludwig Augustinsson",
      "South Korea": "499 Jang Hyun-soo",
      "Belgium": "519 Thomas Meunier",
      "Panama": "539 Adolfo Machado",
      "Tunisia": "559 Yassine Meriah",
      "England": "579 Ryan Bertrand",
      "Poland": "599 Thiago Cionek",
      "Senegal": "619 Saliou Ciss"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "16 Samara Arena",
      "Host cities": "28 Nizhny Novgorod",
      "Russia": "40 Dmitri Kombarov",
      "Saudi Arabia": "60 Motaz Hawsawi",
      "Egypt": "80 Ahmed Abdelmonem Fathy",
      "Uruguay": "100 Gaston Silva",
      "Portugal": "120 Raphael Guerreiro",
      "Spain": "140 Daniel Carvajal",
      "Morocco": "160 Achraf Hakimi",
      "Iran": "180 Ramin Rezaeian",
      "France": "200 Laurent Koscielny",
      "Australia": "220 Ryan McGowan",
      "Peru": "240 Alberto Rodriguez",
      "Denmark": "260 Jens Stryger Larsen",
      "Argentina": "280 Ramiro Funes Mori",
      "Iceland": "300 Hordur Magnusson",
      "Croatia": "320 Vedran Corluka",
      "Nigeria": "340 Ola Aina",
      "Brazil": "360 Marcelo",
      "Switzerland": "380 Fabian Schar",
      "Costa Rica": "400 Ronald Matarrita",
      "Serbia": "420 Nikola Maksimovic",
      "Germany": "440 Julian Draxler",
      "Mexico": "460 Carlos Salcedo",
      "Sweden": "480 Emil Krafth",
      "South Korea": "500 Koo Ja-cheol",
      "Belgium": "520 Axel Witsel",
      "Panama": "540 Eric Davis",
      "Tunisia": "560 Oussama Haddadi",
      "England": "580 Danny Rose",
      "Poland": "600 Bartosz Bereszynski",
      "Senegal": "620 Moussa Wague"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "17 Mordovia Arena",
      "Host cities": "29 Samara",
      "Russia": "41 Aleksei Miranchuk",
      "Saudi Arabia": "61 Mohammed Al-Breik",
      "Egypt": "81 Mohamed Abdel Shafy",
      "Uruguay": "101 Mathias Corujo",
      "Portugal": "121 Joao Moutinho",
      "Spain": "141 Sergio Busquets",
      "Morocco": "161 Mbark Boussoufa",
      "Iran": "181 Ehsan Hajsafi",
      "France": "201 Blaise Matuidi",
      "Australia": "221 Mark Milligan",
      "Peru": "241 Miguel Araujo",
      "Denmark": "261 Peter Ankersen",
      "Argentina": "281 Lucas Biglia",
      "Iceland": "301 Aron Gunnarsson",
      "Croatia": "321 Ivan Rakitic",
      "Nigeria": "341 John Obi Mikel",
      "Brazil": "361 Willian",
      "Switzerland": "381 Granit Xhaka",
      "Costa Rica": "401 Michael Umana",
      "Serbia": "421 Jagos Vukovic",
      "Germany": "441 Toni Kroos",
      "Mexico": "461 Jonathan dos Santos",
      "Sweden": "481 Pontus Jansson",
      "South Korea": "501 Kwon Chang-hoon",
      "Belgium": "521 Radja Nainggolan",
      "Panama": "541 Luis Ovalle",
      "Tunisia": "561 Ferjani Sassi",
      "England": "581 Phil Jones",
      "Poland": "601 Artur Jedrzejczyk",
      "Senegal": "621 Idrissa Gueye"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "18 Fisht Stadium",
      "Host cities": "30 Yekaterinburg",
      "Russia": "42 Denis Glushakov",
      "Saudi Arabia": "62 Taisir Al-Jassim",
      "Egypt": "82 Saad Samir",
      "Uruguay": "102 Egidio Arevalo Rios",
      "Portugal": "122 Joao Mario",
      "Spain": "142 Thiago Alcantara",
      "Morocco": "162 Karim El Ahmadi",
      "Iran": "182 Omid Ebrahimi",
      "France": "202 N'Golo Kante",
      "Australia": "222 Aaron Mooy",
      "Peru": "242 Christian Cueva",
      "Denmark": "262 Riza Durmisi",
      "Argentina": "282 Enzo Perez",
      "Iceland": "302 Birkir Bjarnason",
      "Croatia": "322 Luka Modric",
      "Nigeria": "342 Ogenyi Onazi",
      "Brazil": "362 Paulinho",
      "Switzerland": "382 Steven Zuber",
      "Costa Rica": "402 Johnny Acosta",
      "Serbia": "422 Dusan Tadic",
      "Germany": "442 Emre Can",
      "Mexico": "462 Giovani dos Santos",
      "Sweden": "482 Sebastian Larsson",
      "South Korea": "502 Ki Sung-yueng",
      "Belgium": "522 Kevin De Bruyne",
      "Panama": "542 Felipe Baloy",
      "Tunisia": "562 Wahbi Khazri",
      "England": "582 Jordan Henderson",
      "Poland": "602 Maciej Rybus",
      "Senegal": "622 Cheikhou Kouyate"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "19 Volgograd Arena",
      "Host cities": "31 Saransk",
      "Russia": "43 Aleksandr Golovin",
      "Saudi Arabia": "63 Salman Al-Faraj",
      "Egypt": "83 Tarek Hamed",
      "Uruguay": "103 Alvaro Gonzalez",
      "Portugal": "123 Danilo Pereira",
      "Spain": "143 Isco",
      "Morocco": "163 Younes Belhanda",
      "Iran": "183 Saeid Ezatolahi",
      "France": "203 Thomas Lemar",
      "Australia": "223 James Troisi",
      "Peru": "243 Renato Tapia",
      "Denmark": "263 William Kvist",
      "Argentina": "283 Angel Di Maria",
      "Iceland": "303 Emil Hallfredsson",
      "Croatia": "323 Marcelo Brozovic",
      "Nigeria": "343 Etebo Oghenekaro",
      "Brazil": "363 Fernandinho",
      "Switzerland": "383 Blerim Dzemaili",
      "Costa Rica": "403 Bryan Ruiz",
      "Serbia": "423 Sergej Milinkovic-Savic",
      "Germany": "443 Leon Goretzka",
      "Mexico": "463 Andres Guardado",
      "Sweden": "483 Emil Forsberg",
      "South Korea": "503 Nam Tae-hee",
      "Belgium": "523 Marouane Fellaini",
      "Panama": "543 Gabriel Gomez",
      "Tunisia": "563 Mohamed Amine Ben Amor",
      "England": "583 Alex Oxlade-Chamberlain",
      "Poland": "603 Jakub Blaszczykowski",
      "Senegal": "623 Cheikh Ndoye"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "",
      "Host cities": "",
      "Russia": "44 Yuri Zhirkov",
      "Saudi Arabia": "64 Abdulmalek Al-Khaibri",
      "Egypt": "84 Mahmoud Kahraba",
      "Uruguay": "104 Nicolas Lodeiro",
      "Portugal": "124 William Carvalho",
      "Spain": "144 Koke",
      "Morocco": "164 Nordin Amrabat",
      "Iran": "184 Vahid Amiri",
      "France": "204 Adrien Rabiot",
      "Australia": "224 Mile Jedinak",
      "Peru": "244 Andy Polo",
      "Denmark": "264 Thomas Delaney",
      "Argentina": "284 Marcos Acuna",
      "Iceland": "304 Gylfi Sigurdsson",
      "Croatia": "324 Marko Rog",
      "Nigeria": "344 Wilfred Ndidi",
      "Brazil": "364 Casemiro",
      "Switzerland": "384 Denis Zakaria",
      "Costa Rica": "404 Celso Borges",
      "Serbia": "424 Nemanja Matic",
      "Germany": "444 Julian Brandt",
      "Mexico": "464 Hector Herrera",
      "Sweden": "484 Gustav Svensson",
      "South Korea": "504 Han Kook-young",
      "Belgium": "524 Youri Tielemans",
      "Panama": "544 Edgar Barcenas",
      "Tunisia": "564 Ghailene Chaalali",
      "England": "584 Dele Alli",
      "Poland": "604 Kamil Grosicki",
      "Senegal": "624 Pape Alioune N'Diaye"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "",
      "Host cities": "",
      "Russia": "45 Aleksandr Samedov",
      "Saudi Arabia": "65 Salman Al-Moasher",
      "Egypt": "85 Mohamed Elneny",
      "Uruguay": "105 Carlos Sanchez",
      "Portugal": "125 Andre Gomes",
      "Spain": "145 Marco Asensio",
      "Morocco": "165 Faycal Fajr",
      "Iran": "185 Alireza Jahanbakhsh",
      "France": "205 Paul Pogba",
      "Australia": "225 Massimo Luongo",
      "Peru": "245 Yoshimar Yotun",
      "Denmark": "265 Christian Eriksen",
      "Argentina": "285 Ever Banega",
      "Iceland": "305 Arnor Ingvi Traustason",
      "Croatia": "325 Mario Pasalic",
      "Nigeria": "345 Mikel Agu",
      "Brazil": "365 Renato Augusto",
      "Switzerland": "385 Xherdan Shaqiri",
      "Costa Rica": "405 Christian Bolanos",
      "Serbia": "425 Luka Milivojevic",
      "Germany": "445 Sebastian Rudy",
      "Mexico": "465 Javier Aquino",
      "Sweden": "485 Viktor Claesson",
      "South Korea": "505 Lee Chung-yong",
      "Belgium": "525 Mousa Dembele",
      "Panama": "545 Armando Cooper",
      "Tunisia": "565 Naim Sliti",
      "England": "585 Eric Dier",
      "Poland": "605 Grzegorz Krychowiak",
      "Senegal": "625 Sadio Mane"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "",
      "Host cities": "",
      "Russia": "46 Aleksandr Erokhin",
      "Saudi Arabia": "66 Yahya Al-Shehri",
      "Egypt": "86 Mahmoud Trezeguet",
      "Uruguay": "106 Cristian Rodriguez",
      "Portugal": "126 Ricardo Quaresma",
      "Spain": "146 Andres Iniesta",
      "Morocco": "166 Hakim Ziyech",
      "Iran": "186 Ashkan Dejagah",
      "France": "206 Olivier Giroud",
      "Australia": "226 Jackson Irvine",
      "Peru": "246 Edison Flores",
      "Denmark": "266 Lasse Schone",
      "Argentina": "286 Eduardo Salvio",
      "Iceland": "306 Rurik Gislason",
      "Croatia": "326 Milan Badelj",
      "Nigeria": "346 Ahmed Musa",
      "Brazil": "366 Giuliano",
      "Switzerland": "386 Valon Behrami",
      "Costa Rica": "406 Randall Azofeifa",
      "Serbia": "426 Adem Ljajic",
      "Germany": "446 Leroy Sane",
      "Mexico": "466 Jesus Corona",
      "Sweden": "486 Jimmy Durmaz",
      "South Korea": "506 Jung Woo-young",
      "Belgium": "526 Nacer Chadli",
      "Panama": "546 Alberto Quintero",
      "Tunisia": "566 Youssef Msakni",
      "England": "586 Adam Lallana",
      "Poland": "606 Krzysztof Maczynski",
      "Senegal": "626 Moussa Sow"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "",
      "Host cities": "",
      "Russia": "47 Alan Dzagoev",
      "Saudi Arabia": "67 Salem Al-Dawsari",
      "Egypt": "87 Abdallah Said",
      "Uruguay": "107 Matias Vecino",
      "Portugal": "127 Bernardo Silva",
      "Spain": "147 David Villa",
      "Morocco": "167 Youssef Ait Bennasser",
      "Iran": "187 Saman Ghoddos",
      "France": "207 Antoine Griezmann",
      "Australia": "227 Tom Rogic",
      "Peru": "247 Paolo Hurtado",
      "Denmark": "267 Pione Sisto",
      "Argentina": "287 Mauro Icardi",
      "Iceland": "307 Johann Gudmundsson",
      "Croatia": "327 Mateo Kovacic",
      "Nigeria": "347 Victor Moses",
      "Brazil": "367 Philippe Coutinho",
      "Switzerland": "387 Gelson Fernandes",
      "Costa Rica": "407 David Guzman",
      "Serbia": "427 Nemanja Gudelj",
      "Germany": "447 Mesut Ozil",
      "Mexico": "467 Hirving Lozano",
      "Sweden": "487 Albin Ekdal",
      "South Korea": "507 Lee Jae-sung",
      "Belgium": "527 Eden Hazard",
      "Panama": "547 Anibal Godoy",
      "Tunisia": "567 Fakhreddine Ben Youssef",
      "England": "587 Jesse Lingard",
      "Poland": "607 Piotr Zielinski",
      "Senegal": "627 Moussa Konate"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "",
      "Host cities": "",
      "Russia": "48 Daler Kuzyayev",
      "Saudi Arabia": "68 Nawaf Al-Abed",
      "Egypt": "88 Ramadan Sobhi",
      "Uruguay": "108 Edinson Cavani",
      "Portugal": "128 Andre Silva",
      "Spain": "148 Saul Niguez",
      "Morocco": "168 Khalid Boutaib",
      "Iran": "188 Mehdi Taremi",
      "France": "208 Alexandre Lacazette",
      "Australia": "228 Tim Cahill",
      "Peru": "248 Paolo Guerrero",
      "Denmark": "268 Nicklas Bendtner",
      "Argentina": "288 Lionel Messi",
      "Iceland": "308 Alfred Finnbogason",
      "Croatia": "328 Andrej Kramaric",
      "Nigeria": "348 Moses Simon",
      "Brazil": "368 Douglas Costa",
      "Switzerland": "388 Breel Embolo",
      "Costa Rica": "408 Rodney Wallace",
      "Serbia": "428 Mijat Gacinovic",
      "Germany": "448 Sami Khedira",
      "Mexico": "468 Raul Jimenez",
      "Sweden": "488 Isaac Kiese Thelin",
      "South Korea": "508 Son Heung-min",
      "Belgium": "528 Yannick Carrasco",
      "Panama": "548 Blas Perez",
      "Tunisia": "568 Taha Yassine Khenissi",
      "England": "588 Raheem Sterling",
      "Poland": "608 Karol Linetty",
      "Senegal": "628 Keita Balde"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "",
      "Host cities": "",
      "Russia": "49 Dmitry Poloz",
      "Saudi Arabia": "69 Mohammad Al-Sahlawi",
      "Egypt": "89 Ahmed Hassan",
      "Uruguay": "109 Luis Suarez",
      "Portugal": "129 Gelson Martins",
      "Spain": "149 Alvaro Morata",
      "Morocco": "169 Rachid Alioui",
      "Iran": "189 Karim Ansarifard",
      "France": "209 Kylian Mbappe",
      "Australia": "229 Mathew Leckie",
      "Peru": "249 Jefferson Farfan",
      "Denmark": "269 Nicolai Jorgensen",
      "Argentina": "289 Paulo Dybala",
      "Iceland": "309 Jon Dadi Bodvarsson",
      "Croatia": "329 Nikola Kalinic",
      "Nigeria": "349 Odion Ighalo",
      "Brazil": "369 Roberto Firmino",
      "Switzerland": "389 Haris Seferovic",
      "Costa Rica": "409 Joel Campbell",
      "Serbia": "429 Filip Kostic",
      "Germany": "449 Mario Gotze",
      "Mexico": "469 Carlos Vela",
      "Sweden": "489 Marcus Berg",
      "South Korea": "509 Ji Dong-won",
      "Belgium": "529 Dries Mertens",
      "Panama": "549 Gabriel Torres",
      "Tunisia": "569 Yoann Touzghar",
      "England": "589 Harry Kane",
      "Poland": "609 Robert Lewandowski",
      "Senegal": "629 M'Baye Niang"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "",
      "Host cities": "",
      "Russia": "50 Fedor Smolov",
      "Saudi Arabia": "70 Nasser Al-Shamrani",
      "Egypt": "90 Mohamed Salah",
      "Uruguay": "110 Cristhian Stuani",
      "Portugal": "130 Cristiano Ronaldo",
      "Spain": "150 Vitolo",
      "Morocco": "170 Aziz Bouhaddouz",
      "Iran": "190 Reza Ghoochannejhad",
      "France": "210 Ousmane Dembele",
      "Australia": "230 Tomi Juric",
      "Peru": "250 Raul Ruidiaz",
      "Denmark": "270 Yussuf Poulsen",
      "Argentina": "290 Sergio Aguero",
      "Iceland": "310 Vidar Orn Kjartansson",
      "Croatia": "330 Mario Mandzukic",
      "Nigeria": "350 Alex Iwobi",
      "Brazil": "370 Gabriel Jesus",
      "Switzerland": "390 Admir Mehmedi",
      "Costa Rica": "410 Marco Urena",
      "Serbia": "430 Aleksandar Mitrovic",
      "Germany": "450 Thomas Muller",
      "Mexico": "470 Javier Hernandez",
      "Sweden": "490 John Guidetti",
      "South Korea": "510 Kim Shin-wook",
      "Belgium": "530 Michy Batshuayi",
      "Panama": "550 Luis Tejada",
      "Tunisia": "570 Anice Badri",
      "England": "590 Marcus Rashford",
      "Poland": "610 Lukasz Teodorczyk",
      "Senegal": "630 Ismaila Sarr"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "",
      "Host cities": "",
      "Russia": "51 Aleksandr Kokorin",
      "Saudi Arabia": "71 Fahad Al-Muwallad",
      "Egypt": "91 Amr Gamal",
      "Uruguay": "111 Diego Rolan",
      "Portugal": "131 Nani",
      "Spain": "151 Diego Costa",
      "Morocco": "171 Youssef En-Nesyri",
      "Iran": "191 Sardar Azmoun",
      "France": "211 Anthony Martial",
      "Australia": "231 Robbie Kruse",
      "Peru": "251 Andre Carrillo",
      "Denmark": "271 Andreas Cornelius",
      "Argentina": "291 Gonzalo Higuain",
      "Iceland": "311 Bjorn Sigurdarson",
      "Croatia": "331 Ivan Perisic",
      "Nigeria": "351 Kelechi Iheanacho",
      "Brazil": "371 Neymar Jr",
      "Switzerland": "391 Eren Derdiyok",
      "Costa Rica": "411 Johan Venegas",
      "Serbia": "431 Aleksandar Prijovic",
      "Germany": "451 Timo Werner",
      "Mexico": "471 Oribe Peralta",
      "Sweden": "491 Ola Toivonen",
      "South Korea": "511 Hwang Hee-chan",
      "Belgium": "531 Romelu Lukaku",
      "Panama": "551 Abdiel Arroyo",
      "Tunisia": "571 Ahmed Akaichi",
      "England": "591 Jamie Vardy",
      "Poland": "611 Arkadiusz Milik",
      "Senegal": "631 Mame Diouf"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "",
      "Host cities": "",
      "Russia": "",
      "Saudi Arabia": "",
      "Egypt": "",
      "Uruguay": "",
      "Portugal": "",
      "Spain": "",
      "Morocco": "",
      "Iran": "",
      "France": "",
      "Australia": "",
      "Peru": "",
      "Denmark": "",
      "Argentina": "",
      "Iceland": "",
      "Croatia": "",
      "Nigeria": "",
      "Brazil": "",
      "Switzerland": "",
      "Costa Rica": "",
      "Serbia": "",
      "Germany": "",
      "Mexico": "",
      "Sweden": "",
      "South Korea": "",
      "Belgium": "",
      "Panama": "",
      "Tunisia": "",
      "England": "",
      "Poland": "",
      "Senegal": ""
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "",
      "Host cities": "",
      "Russia": "",
      "Saudi Arabia": "",
      "Egypt": "",
      "Uruguay": "",
      "Portugal": "",
      "Spain": "",
      "Morocco": "",
      "Iran": "",
      "France": "",
      "Australia": "",
      "Peru": "",
      "Denmark": "",
      "Argentina": "",
      "Iceland": "",
      "Croatia": "",
      "Nigeria": "",
      "Brazil": "",
      "Switzerland": "",
      "Costa Rica": "",
      "Serbia": "",
      "Germany": "",
      "Mexico": "",
      "Sweden": "",
      "South Korea": "",
      "Belgium": "",
      "Panama": "",
      "Tunisia": "",
      "England": "",
      "Poland": "",
      "Senegal": ""
    }
  ]`;


const jsonData = JSON.parse(rawData);
const formattedData = {};

jsonData.forEach(group => {
    for (let key in group) {
        formattedData[key] = formattedData[String(key)] || [];
        if (group[key]) {
            const item = group[key].split(' ');
            formattedData[key].push({
                id: item.shift(), // takes away 1st element
                name: item.join(' ')
            });
            
            // console.log(item)
        }
    } 
});

console.log(JSON.stringify(formattedData))

const data = `{"Trophy, Official Ball & Logos":[{"id":"0","name":"Panini Logo"},{"id":"1","name":"FIFA Logo"},{"id":"2","name":"World Cup Trophy"},{"id":"3","name":"2018 World Cup Graphic 1"},{"id":"4","name":"2018 World Cup Graphic 2"},{"id":"5","name":"2018 World Cup Logo 1"},{"id":"6","name":"2018 World Cup Logo 2"},{"id":"7","name":"Official Ball"}],"Stadia":[{"id":"8","name":"Ekaterinburg Arena"},{"id":"9","name":"Kaliningrad Stadium"},{"id":"10","name":"Kazan Arena"},{"id":"11","name":"Spartak Stadium"},{"id":"12","name":"Nizhny Novgorod Stadium"},{"id":"13","name":"Luzhniki Stadium"},{"id":"14","name":"Rostov Arena"},{"id":"15","name":"Saint Petersburg Stadium"},{"id":"16","name":"Samara Arena"},{"id":"17","name":"Mordovia Arena"},{"id":"18","name":"Fisht Stadium"},{"id":"19","name":"Volgograd Arena"}],"Host cities":[{"id":"20","name":"Moscow 1"},{"id":"21","name":"Moscow 2"},{"id":"22","name":"Kaliningrad"},{"id":"23","name":"Saint Petersburg"},{"id":"24","name":"Sochi"},{"id":"25","name":"Rostov-on-Don"},{"id":"26","name":"Volgograd"},{"id":"27","name":"Kazan"},{"id":"28","name":"Nizhny Novgorod"},{"id":"29","name":"Samara"},{"id":"30","name":"Yekaterinburg"},{"id":"31","name":"Saransk"}],"Russia":[{"id":"32","name":"Team Logo - Russia"},{"id":"33","name":"Team Photo - Russia"},{"id":"34","name":"Igor Akinfeev"},{"id":"35","name":"Igor Smolnikov"},{"id":"36","name":"Viktor Vasin"},{"id":"37","name":"Mario Fernandes"},{"id":"38","name":"Fedor Kudryashov"},{"id":"39","name":"Ilya Kutepov"},{"id":"40","name":"Dmitri Kombarov"},{"id":"41","name":"Aleksei Miranchuk"},{"id":"42","name":"Denis Glushakov"},{"id":"43","name":"Aleksandr Golovin"},{"id":"44","name":"Yuri Zhirkov"},{"id":"45","name":"Aleksandr Samedov"},{"id":"46","name":"Aleksandr Erokhin"},{"id":"47","name":"Alan Dzagoev"},{"id":"48","name":"Daler Kuzyayev"},{"id":"49","name":"Dmitry Poloz"},{"id":"50","name":"Fedor Smolov"},{"id":"51","name":"Aleksandr Kokorin"}],"Saudi Arabia":[{"id":"52","name":"Team Logo - Saudi Arabia"},{"id":"53","name":"Team Photo - Saudi Arabia"},{"id":"54","name":"Abdullah Al-Mayouf"},{"id":"55","name":"Osama Hawsawi"},{"id":"56","name":"Abdullah Al-Zori"},{"id":"57","name":"Mansoor Al-Harbi"},{"id":"58","name":"Omar Hawsawi"},{"id":"59","name":"Yasser Al-Shahrani"},{"id":"60","name":"Motaz Hawsawi"},{"id":"61","name":"Mohammed Al-Breik"},{"id":"62","name":"Taisir Al-Jassim"},{"id":"63","name":"Salman Al-Faraj"},{"id":"64","name":"Abdulmalek Al-Khaibri"},{"id":"65","name":"Salman Al-Moasher"},{"id":"66","name":"Yahya Al-Shehri"},{"id":"67","name":"Salem Al-Dawsari"},{"id":"68","name":"Nawaf Al-Abed"},{"id":"69","name":"Mohammad Al-Sahlawi"},{"id":"70","name":"Nasser Al-Shamrani"},{"id":"71","name":"Fahad Al-Muwallad"}],"Egypt":[{"id":"72","name":"Team Logo - Egypt"},{"id":"73","name":"Team Photo - Egypt"},{"id":"74","name":"Essam El Hadary"},{"id":"75","name":"Ali Gabr"},{"id":"76","name":"Ahmed El Mohamady"},{"id":"77","name":"Omar Gaber"},{"id":"78","name":"Ramy Rabia"},{"id":"79","name":"Ahmed Hegazi"},{"id":"80","name":"Ahmed Abdelmonem Fathy"},{"id":"81","name":"Mohamed Abdel Shafy"},{"id":"82","name":"Saad Samir"},{"id":"83","name":"Tarek Hamed"},{"id":"84","name":"Mahmoud Kahraba"},{"id":"85","name":"Mohamed Elneny"},{"id":"86","name":"Mahmoud Trezeguet"},{"id":"87","name":"Abdallah Said"},{"id":"88","name":"Ramadan Sobhi"},{"id":"89","name":"Ahmed Hassan"},{"id":"90","name":"Mohamed Salah"},{"id":"91","name":"Amr Gamal"}],"Uruguay":[{"id":"92","name":"Team Logo - Uruguay"},{"id":"93","name":"Team Photo - Uruguay"},{"id":"94","name":"Fernando Muslera"},{"id":"95","name":"Maxi Pereira"},{"id":"96","name":"Diego Godin"},{"id":"97","name":"Martin Caceres"},{"id":"98","name":"Jose Gimenez"},{"id":"99","name":"Sebastian Coates"},{"id":"100","name":"Gaston Silva"},{"id":"101","name":"Mathias Corujo"},{"id":"102","name":"Egidio Arevalo Rios"},{"id":"103","name":"Alvaro Gonzalez"},{"id":"104","name":"Nicolas Lodeiro"},{"id":"105","name":"Carlos Sanchez"},{"id":"106","name":"Cristian Rodriguez"},{"id":"107","name":"Matias Vecino"},{"id":"108","name":"Edinson Cavani"},{"id":"109","name":"Luis Suarez"},{"id":"110","name":"Cristhian Stuani"},{"id":"111","name":"Diego Rolan"}],"Portugal":[{"id":"112","name":"Team Logo - Portugal"},{"id":"113","name":"Team Photo - Portugal"},{"id":"114","name":"RuiPatricio"},{"id":"115","name":"Bruno Alves"},{"id":"116","name":"Pepe"},{"id":"117","name":"Jose Fonte"},{"id":"118","name":"Eliseu"},{"id":"119","name":"Cedric"},{"id":"120","name":"Raphael Guerreiro"},{"id":"121","name":"Joao Moutinho"},{"id":"122","name":"Joao Mario"},{"id":"123","name":"Danilo Pereira"},{"id":"124","name":"William Carvalho"},{"id":"125","name":"Andre Gomes"},{"id":"126","name":"Ricardo Quaresma"},{"id":"127","name":"Bernardo Silva"},{"id":"128","name":"Andre Silva"},{"id":"129","name":"Gelson Martins"},{"id":"130","name":"Cristiano Ronaldo"},{"id":"131","name":"Nani"}],"Spain":[{"id":"132","name":"Team Logo - Spain"},{"id":"133","name":"Team Photo - Spain"},{"id":"134","name":"David de Gea"},{"id":"135","name":"Jordi Alba"},{"id":"136","name":"Nacho"},{"id":"137","name":"Nacho Monreal"},{"id":"138","name":"Gerard Pique"},{"id":"139","name":"Sergio Ramos"},{"id":"140","name":"Daniel Carvajal"},{"id":"141","name":"Sergio Busquets"},{"id":"142","name":"Thiago Alcantara"},{"id":"143","name":"Isco"},{"id":"144","name":"Koke"},{"id":"145","name":"Marco Asensio"},{"id":"146","name":"Andres Iniesta"},{"id":"147","name":"David Villa"},{"id":"148","name":"Saul Niguez"},{"id":"149","name":"Alvaro Morata"},{"id":"150","name":"Vitolo"},{"id":"151","name":"Diego Costa"}],"Morocco":[{"id":"152","name":"Team Logo - Morocco"},{"id":"153","name":"Team Photo - Morocco"},{"id":"154","name":"Munir Mohamedi"},{"id":"155","name":"Medhi Benatia"},{"id":"156","name":"Nabil Dirar"},{"id":"157","name":"Romain Saiss"},{"id":"158","name":"Fouad Chafik"},{"id":"159","name":"Hamza Mendyl"},{"id":"160","name":"Achraf Hakimi"},{"id":"161","name":"Mbark Boussoufa"},{"id":"162","name":"Karim El Ahmadi"},{"id":"163","name":"Younes Belhanda"},{"id":"164","name":"Nordin Amrabat"},{"id":"165","name":"Faycal Fajr"},{"id":"166","name":"Hakim Ziyech"},{"id":"167","name":"Youssef Ait Bennasser"},{"id":"168","name":"Khalid Boutaib"},{"id":"169","name":"Rachid Alioui"},{"id":"170","name":"Aziz Bouhaddouz"},{"id":"171","name":"Youssef En-Nesyri"}],"Iran":[{"id":"172","name":"Team Logo - Iran"},{"id":"173","name":"Team Photo - Iran"},{"id":"174","name":"Alireza Beiranvand"},{"id":"175","name":"Pejman Montazeri"},{"id":"176","name":"Vouria Ghafouri"},{"id":"177","name":"Jalal Hosseini"},{"id":"178","name":"Milad Mohammadi"},{"id":"179","name":"Morteza Pouraliganji"},{"id":"180","name":"Ramin Rezaeian"},{"id":"181","name":"Ehsan Hajsafi"},{"id":"182","name":"Omid Ebrahimi"},{"id":"183","name":"Saeid Ezatolahi"},{"id":"184","name":"Vahid Amiri"},{"id":"185","name":"Alireza Jahanbakhsh"},{"id":"186","name":"Ashkan Dejagah"},{"id":"187","name":"Saman Ghoddos"},{"id":"188","name":"Mehdi Taremi"},{"id":"189","name":"Karim Ansarifard"},{"id":"190","name":"Reza Ghoochannejhad"},{"id":"191","name":"Sardar Azmoun"}],"France":[{"id":"192","name":"Team Logo - France"},{"id":"193","name":"Team Photo - France"},{"id":"194","name":"Hugo Lloris"},{"id":"195","name":"Raphael Varane"},{"id":"196","name":"Lucas Digne"},{"id":"197","name":"Djibril Sidibe"},{"id":"198","name":"Samuel Umtiti"},{"id":"199","name":"Layvin Kurzawa"},{"id":"200","name":"Laurent Koscielny"},{"id":"201","name":"Blaise Matuidi"},{"id":"202","name":"N'Golo Kante"},{"id":"203","name":"Thomas Lemar"},{"id":"204","name":"Adrien Rabiot"},{"id":"205","name":"Paul Pogba"},{"id":"206","name":"Olivier Giroud"},{"id":"207","name":"Antoine Griezmann"},{"id":"208","name":"Alexandre Lacazette"},{"id":"209","name":"Kylian Mbappe"},{"id":"210","name":"Ousmane Dembele"},{"id":"211","name":"Anthony Martial"}],"Australia":[{"id":"212","name":"TeamLogo - Australia"},{"id":"213","name":"Team Photo - Australia"},{"id":"214","name":"Mathew Ryan"},{"id":"215","name":"Mitchell Langerak"},{"id":"216","name":"Milos Degenek"},{"id":"217","name":"Bailey Wright"},{"id":"218","name":"Aziz Behich"},{"id":"219","name":"Trent Sainsbury"},{"id":"220","name":"Ryan McGowan"},{"id":"221","name":"Mark Milligan"},{"id":"222","name":"Aaron Mooy"},{"id":"223","name":"James Troisi"},{"id":"224","name":"Mile Jedinak"},{"id":"225","name":"Massimo Luongo"},{"id":"226","name":"Jackson Irvine"},{"id":"227","name":"Tom Rogic"},{"id":"228","name":"Tim Cahill"},{"id":"229","name":"Mathew Leckie"},{"id":"230","name":"Tomi Juric"},{"id":"231","name":"Robbie Kruse"}],"Peru":[{"id":"232","name":"Team Logo - Peur"},{"id":"233","name":"Team Photo - Peru"},{"id":"234","name":"Pedro Gallese"},{"id":"235","name":"Carlos Caceda"},{"id":"236","name":"Aldo Corzo"},{"id":"237","name":"Miguel Trauco"},{"id":"238","name":"Christian Ramos"},{"id":"239","name":"Luis Advincula"},{"id":"240","name":"Alberto Rodriguez"},{"id":"241","name":"Miguel Araujo"},{"id":"242","name":"Christian Cueva"},{"id":"243","name":"Renato Tapia"},{"id":"244","name":"Andy Polo"},{"id":"245","name":"Yoshimar Yotun"},{"id":"246","name":"Edison Flores"},{"id":"247","name":"Paolo Hurtado"},{"id":"248","name":"Paolo Guerrero"},{"id":"249","name":"Jefferson Farfan"},{"id":"250","name":"Raul Ruidiaz"},{"id":"251","name":"Andre Carrillo"}],"Denmark":[{"id":"252","name":"Team Logo - Denmark"},{"id":"253","name":"Team Photo - Denmark"},{"id":"254","name":"Kasper Schmeichel"},{"id":"255","name":"Jannik Vestergaard"},{"id":"256","name":"Simon Kjaer"},{"id":"257","name":"Andreas Christensen"},{"id":"258","name":"Andreas Bjelland"},{"id":"259","name":"Mathias Jorgensen"},{"id":"260","name":"Jens Stryger Larsen"},{"id":"261","name":"Peter Ankersen"},{"id":"262","name":"Riza Durmisi"},{"id":"263","name":"William Kvist"},{"id":"264","name":"Thomas Delaney"},{"id":"265","name":"Christian Eriksen"},{"id":"266","name":"Lasse Schone"},{"id":"267","name":"Pione Sisto"},{"id":"268","name":"Nicklas Bendtner"},{"id":"269","name":"Nicolai Jorgensen"},{"id":"270","name":"Yussuf Poulsen"},{"id":"271","name":"Andreas Cornelius"}],"Argentina":[{"id":"272","name":"Team Logo - Argentina"},{"id":"273","name":"Team Photo - Argentina"},{"id":"274","name":"Sergio Romero"},{"id":"275","name":"Gabriel Mercado"},{"id":"276","name":"Federico Fazio"},{"id":"277","name":"Javier Mascherano"},{"id":"278","name":"Nicolas Otamendi"},{"id":"279","name":"Marcos Rojo"},{"id":"280","name":"Ramiro Funes Mori"},{"id":"281","name":"Lucas Biglia"},{"id":"282","name":"Enzo Perez"},{"id":"283","name":"Angel Di Maria"},{"id":"284","name":"Marcos Acuna"},{"id":"285","name":"Ever Banega"},{"id":"286","name":"Eduardo Salvio"},{"id":"287","name":"Mauro Icardi"},{"id":"288","name":"Lionel Messi"},{"id":"289","name":"PauloDybala"},{"id":"290","name":"Sergio Aguero"},{"id":"291","name":"Gonzalo Higuain"}],"Iceland":[{"id":"292","name":"Team Logo - Iceland"},{"id":"293","name":"Team Photo - Iceland"},{"id":"294","name":"Hannes Halldorsson"},{"id":"295","name":"Birkir Saevarsson"},{"id":"296","name":"Ragnar Sigurosson"},{"id":"297","name":"Kari Arnason"},{"id":"298","name":"Ari Skulason"},{"id":"299","name":"Sverrir Ingason"},{"id":"300","name":"Hordur Magnusson"},{"id":"301","name":"Aron Gunnarsson"},{"id":"302","name":"Birkir Bjarnason"},{"id":"303","name":"Emil Hallfredsson"},{"id":"304","name":"Gylfi Sigurdsson"},{"id":"305","name":"Arnor Ingvi Traustason"},{"id":"306","name":"Rurik Gislason"},{"id":"307","name":"Johann Gudmundsson"},{"id":"308","name":"Alfred Finnbogason"},{"id":"309","name":"Jon Dadi Bodvarsson"},{"id":"310","name":"Vidar Orn Kjartansson"},{"id":"311","name":"Bjorn Sigurdarson"}],"Croatia":[{"id":"312","name":"Team Logo - Croatia"},{"id":"313","name":"Team Photo - Croatia"},{"id":"314","name":"Danijel Subasic"},{"id":"315","name":"Sime Vrsaljko"},{"id":"316","name":"Ivan Strinic"},{"id":"317","name":"Dejan Lovren"},{"id":"318","name":"Domagoj Vida"},{"id":"319","name":"Josip Pivaric"},{"id":"320","name":"Vedran Corluka"},{"id":"321","name":"Ivan Rakitic"},{"id":"322","name":"Luka Modric"},{"id":"323","name":"Marcelo Brozovic"},{"id":"324","name":"Marko Rog"},{"id":"325","name":"Mario Pasalic"},{"id":"326","name":"Milan Badelj"},{"id":"327","name":"Mateo Kovacic"},{"id":"328","name":"Andrej Kramaric"},{"id":"329","name":"Nikola Kalinic"},{"id":"330","name":"Mario Mandzukic"},{"id":"331","name":"Ivan Perisic"}],"Nigeria":[{"id":"332","name":"Team Logo - Nigeria"},{"id":"333","name":"Team Photo - Nigeria"},{"id":"334","name":"Ikechukwu Ezenwa"},{"id":"335","name":"Elderson Echiejile"},{"id":"336","name":"Shehu Abdullahi"},{"id":"337","name":"William Troost-Ekong"},{"id":"338","name":"Leon Balogun"},{"id":"339","name":"Kenneth Omeruo"},{"id":"340","name":"Ola Aina"},{"id":"341","name":"John Obi Mikel"},{"id":"342","name":"Ogenyi Onazi"},{"id":"343","name":"Etebo Oghenekaro"},{"id":"344","name":"Wilfred Ndidi"},{"id":"345","name":"Mikel Agu"},{"id":"346","name":"Ahmed Musa"},{"id":"347","name":"Victor Moses"},{"id":"348","name":"Moses Simon"},{"id":"349","name":"Odion Ighalo"},{"id":"350","name":"Alex Iwobi"},{"id":"351","name":"Kelechi Iheanacho"}],"Brazil":[{"id":"352","name":"Team Logo - Brazil"},{"id":"353","name":"TeamPhoto - Brazil"},{"id":"354","name":"Alisson"},{"id":"355","name":"Dani Alves"},{"id":"356","name":"Thiago Silva"},{"id":"357","name":"Miranda"},{"id":"358","name":"Filipe Luis"},{"id":"359","name":"Marquinhos"},{"id":"360","name":"Marcelo"},{"id":"361","name":"Willian"},{"id":"362","name":"Paulinho"},{"id":"363","name":"Fernandinho"},{"id":"364","name":"Casemiro"},{"id":"365","name":"Renato Augusto"},{"id":"366","name":"Giuliano"},{"id":"367","name":"Philippe Coutinho"},{"id":"368","name":"Douglas Costa"},{"id":"369","name":"Roberto Firmino"},{"id":"370","name":"Gabriel Jesus"},{"id":"371","name":"Neymar Jr"}],"Switzerland":[{"id":"372","name":"Team Logo - Switzerland"},{"id":"373","name":"Team Photo - Switzerland"},{"id":"374","name":"Yann Sommer"},{"id":"375","name":"Stephan Lichtsteiner"},{"id":"376","name":"Manuel Akanji"},{"id":"377","name":"Michael Lang"},{"id":"378","name":"Ricardo Rodriguez"},{"id":"379","name":"Johan Djourou"},{"id":"380","name":"Fabian Schar"},{"id":"381","name":"Granit Xhaka"},{"id":"382","name":"Steven Zuber"},{"id":"383","name":"Blerim Dzemaili"},{"id":"384","name":"Denis Zakaria"},{"id":"385","name":"Xherdan Shaqiri"},{"id":"386","name":"Valon Behrami"},{"id":"387","name":"Gelson Fernandes"},{"id":"388","name":"Breel Embolo"},{"id":"389","name":"Haris Seferovic"},{"id":"390","name":"Admir Mehmedi"},{"id":"391","name":"Eren Derdiyok"}],"Costa Rica":[{"id":"392","name":"Team Logo - Costa Rica"},{"id":"393","name":"Team Photo - Costa Rica"},{"id":"394","name":"Keylor Navas"},{"id":"395","name":"Giancarlo Gonzalez"},{"id":"396","name":"Cristian Gamboa"},{"id":"397","name":"Bryan Oviedo"},{"id":"398","name":"Francisco Calvo"},{"id":"399","name":"Kendall Waston"},{"id":"400","name":"Ronald Matarrita"},{"id":"401","name":"Michael Umana"},{"id":"402","name":"Johnny Acosta"},{"id":"403","name":"Bryan Ruiz"},{"id":"404","name":"Celso Borges"},{"id":"405","name":"Christian Bolanos"},{"id":"406","name":"Randall Azofeifa"},{"id":"407","name":"David Guzman"},{"id":"408","name":"Rodney Wallace"},{"id":"409","name":"Joel Campbell"},{"id":"410","name":"Marco Urena"},{"id":"411","name":"Johan Venegas"}],"Serbia":[{"id":"412","name":"Team Logo - Serbia"},{"id":"413","name":"Team Photo - Serbia"},{"id":"414","name":"Vladimir Stojkovic"},{"id":"415","name":"Branislav Ivanovic"},{"id":"416","name":"Aleksandar Kolarov"},{"id":"417","name":"Antonio Rukavina"},{"id":"418","name":"Matija Nastasic"},{"id":"419","name":"Dusko Tosic"},{"id":"420","name":"Nikola Maksimovic"},{"id":"421","name":"Jagos Vukovic"},{"id":"422","name":"Dusan Tadic"},{"id":"423","name":"Sergej Milinkovic-Savic"},{"id":"424","name":"Nemanja Matic"},{"id":"425","name":"Luka Milivojevic"},{"id":"426","name":"Adem Ljajic"},{"id":"427","name":"Nemanja Gudelj"},{"id":"428","name":"Mijat Gacinovic"},{"id":"429","name":"Filip Kostic"},{"id":"430","name":"Aleksandar Mitrovic"},{"id":"431","name":"Aleksandar Prijovic"}],"Germany":[{"id":"432","name":"Team Logo - Germany"},{"id":"433","name":"Team Photo - Germany"},{"id":"434","name":"Manuel Neuer"},{"id":"435","name":"Mats Hummels"},{"id":"436","name":"Antonio Rudiger"},{"id":"437","name":"Jerome Boateng"},{"id":"438","name":"Joshua Kimmich"},{"id":"439","name":"Jonas Hector"},{"id":"440","name":"Julian Draxler"},{"id":"441","name":"Toni Kroos"},{"id":"442","name":"Emre Can"},{"id":"443","name":"Leon Goretzka"},{"id":"444","name":"Julian Brandt"},{"id":"445","name":"Sebastian Rudy"},{"id":"446","name":"Leroy Sane"},{"id":"447","name":"Mesut Ozil"},{"id":"448","name":"Sami Khedira"},{"id":"449","name":"Mario Gotze"},{"id":"450","name":"Thomas Muller"},{"id":"451","name":"Timo Werner"}],"Mexico":[{"id":"452","name":"Team Logo - Mexico"},{"id":"453","name":"Team Photo - Mexico"},{"id":"454","name":"Guillermo Ochoa"},{"id":"455","name":"Hugo Ayala"},{"id":"456","name":"Diego Reyes"},{"id":"457","name":"Hector Moreno"},{"id":"458","name":"Jesus Gallardo"},{"id":"459","name":"Miguel Layun"},{"id":"460","name":"Carlos Salcedo"},{"id":"461","name":"Jonathan dos Santos"},{"id":"462","name":"Giovani dos Santos"},{"id":"463","name":"Andres Guardado"},{"id":"464","name":"Hector Herrera"},{"id":"465","name":"Javier Aquino"},{"id":"466","name":"Jesus Corona"},{"id":"467","name":"Hirving Lozano"},{"id":"468","name":"Raul Jimenez"},{"id":"469","name":"Carlos Vela"},{"id":"470","name":"Javier Hernandez"},{"id":"471","name":"Oribe Peralta"}],"Sweden":[{"id":"472","name":"Team Logo - Sweden"},{"id":"473","name":"Team Photo - Sweden"},{"id":"474","name":"Robin Olsen"},{"id":"475","name":"Mikael Lustig"},{"id":"476","name":"Victor Nilsson Lindelof"},{"id":"478","name":"Andreas Granqvist"},{"id":"478","name":"Martin Olsson"},{"id":"479","name":"Ludwig Augustinsson"},{"id":"480","name":"Emil Krafth"},{"id":"481","name":"Pontus Jansson"},{"id":"482","name":"Sebastian Larsson"},{"id":"483","name":"Emil Forsberg"},{"id":"484","name":"Gustav Svensson"},{"id":"485","name":"Viktor Claesson"},{"id":"486","name":"Jimmy Durmaz"},{"id":"487","name":"Albin Ekdal"},{"id":"488","name":"Isaac Kiese Thelin"},{"id":"489","name":"Marcus Berg"},{"id":"490","name":"John Guidetti"},{"id":"491","name":"Ola Toivonen"}],"South Korea":[{"id":"492","name":"Team Logo - South Korea"},{"id":"493","name":"Team Photo - South Korea"},{"id":"494","name":"Kim Seung-gyu"},{"id":"495","name":"Kim Young-gwon"},{"id":"496","name":"Kim Jin-su"},{"id":"497","name":"Kwak Tae-hwi"},{"id":"498","name":"Hong Jeong-ho"},{"id":"499","name":"Jang Hyun-soo"},{"id":"500","name":"Koo Ja-cheol"},{"id":"501","name":"Kwon Chang-hoon"},{"id":"502","name":"Ki Sung-yueng"},{"id":"503","name":"Nam Tae-hee"},{"id":"504","name":"Han Kook-young"},{"id":"505","name":"Lee Chung-yong"},{"id":"506","name":"Jung Woo-young"},{"id":"507","name":"Lee Jae-sung"},{"id":"508","name":"Son Heung-min"},{"id":"509","name":"Ji Dong-won"},{"id":"510","name":"Kim Shin-wook"},{"id":"511","name":"Hwang Hee-chan"}],"Belgium":[{"id":"512","name":"Team Logo - Belgium"},{"id":"513","name":"Team Photo - Belgium"},{"id":"514","name":"Thibaut Courtois"},{"id":"515","name":"Toby Alderweireld"},{"id":"516","name":"Thomas Vermaelen"},{"id":"517","name":"Jan Vertonghen"},{"id":"518","name":"Vincent Kompany"},{"id":"519","name":"Thomas Meunier"},{"id":"520","name":"Axel Witsel"},{"id":"521","name":"Radja Nainggolan"},{"id":"522","name":"Kevin De Bruyne"},{"id":"523","name":"Marouane Fellaini"},{"id":"524","name":"Youri Tielemans"},{"id":"525","name":"Mousa Dembele"},{"id":"526","name":"Nacer Chadli"},{"id":"527","name":"Eden Hazard"},{"id":"528","name":"Yannick Carrasco"},{"id":"529","name":"Dries Mertens"},{"id":"530","name":"Michy Batshuayi"},{"id":"531","name":"Romelu Lukaku"}],"Panama":[{"id":"532","name":"Team Logo - Panama"},{"id":"533","name":"Team Photo - Panama"},{"id":"534","name":"Jaime Penedo"},{"id":"535","name":"Jose Calderon"},{"id":"536","name":"Michael Murillo"},{"id":"537","name":"Fidel Escobar"},{"id":"538","name":"Roman Torres"},{"id":"539","name":"Adolfo Machado"},{"id":"540","name":"Eric Davis"},{"id":"541","name":"Luis Ovalle"},{"id":"542","name":"Felipe Baloy"},{"id":"543","name":"Gabriel Gomez"},{"id":"544","name":"Edgar Barcenas"},{"id":"545","name":"Armando Cooper"},{"id":"546","name":"Alberto Quintero"},{"id":"547","name":"Anibal Godoy"},{"id":"548","name":"Blas Perez"},{"id":"549","name":"Gabriel Torres"},{"id":"550","name":"Luis Tejada"},{"id":"551","name":"Abdiel Arroyo"}],"Tunisia":[{"id":"552","name":"Team Logo - Tunisia"},{"id":"553","name":"Team Photo - Tunisia"},{"id":"554","name":"Aymen Mathlouthi"},{"id":"555","name":"Ali Maaloul"},{"id":"556","name":"Syam Ben Youssef"},{"id":"557","name":"Aymen Abdennour"},{"id":"558","name":"Hamdi Nagguez"},{"id":"559","name":"Yassine Meriah"},{"id":"560","name":"Oussama Haddadi"},{"id":"561","name":"Ferjani Sassi"},{"id":"562","name":"Wahbi Khazri"},{"id":"563","name":"Mohamed Amine Ben Amor"},{"id":"564","name":"Ghailene Chaalali"},{"id":"565","name":"Naim Sliti"},{"id":"566","name":"Youssef Msakni"},{"id":"567","name":"Fakhreddine Ben Youssef"},{"id":"568","name":"Taha Yassine Khenissi"},{"id":"569","name":"Yoann Touzghar"},{"id":"570","name":"Anice Badri"},{"id":"571","name":"Ahmed Akaichi"}],"England":[{"id":"572","name":"Team Logo - England"},{"id":"573","name":"Team Photo - England"},{"id":"574","name":"Joe Hart"},{"id":"575","name":"Jordan Pickford"},{"id":"576","name":"Gary Cahill"},{"id":"577","name":"Kyle Walker"},{"id":"578","name":"John Stones"},{"id":"579","name":"Ryan Bertrand"},{"id":"580","name":"Danny Rose"},{"id":"581","name":"Phil Jones"},{"id":"582","name":"Jordan Henderson"},{"id":"583","name":"Alex Oxlade-Chamberlain"},{"id":"584","name":"Dele Alli"},{"id":"585","name":"Eric Dier"},{"id":"586","name":"Adam Lallana"},{"id":"587","name":"Jesse Lingard"},{"id":"588","name":"Raheem Sterling"},{"id":"589","name":"Harry Kane"},{"id":"590","name":"Marcus Rashford"},{"id":"591","name":"Jamie Vardy"}],"Poland":[{"id":"592","name":"Team Logo - Poland"},{"id":"593","name":"Team Photo - Poland"},{"id":"594","name":"Lukasz Fabianski"},{"id":"595","name":"Wojciech Szczesny"},{"id":"596","name":"Lukasz Piszczek"},{"id":"597","name":"Kamil Glik"},{"id":"598","name":"Michal Pazdan"},{"id":"599","name":"Thiago Cionek"},{"id":"600","name":"Bartosz Bereszynski"},{"id":"601","name":"Artur Jedrzejczyk"},{"id":"602","name":"Maciej Rybus"},{"id":"603","name":"Jakub Blaszczykowski"},{"id":"604","name":"Kamil Grosicki"},{"id":"605","name":"Grzegorz Krychowiak"},{"id":"606","name":"Krzysztof Maczynski"},{"id":"607","name":"Piotr Zielinski"},{"id":"608","name":"Karol Linetty"},{"id":"609","name":"Robert Lewandowski"},{"id":"610","name":"Lukasz Teodorczyk"},{"id":"611","name":"Arkadiusz Milik"}],"Senegal":[{"id":"612","name":"Team Logo - Senegal"},{"id":"613","name":"Team Photo - Senegal"},{"id":"614","name":"Khadim N'Diaye"},{"id":"615","name":"Kara Mbodji"},{"id":"616","name":"Lamine Gassama"},{"id":"617","name":"Kalidou Koulibaly"},{"id":"618","name":"Salif Sane"},{"id":"619","name":"Saliou Ciss"},{"id":"620","name":"Moussa Wague"},{"id":"621","name":"Idrissa Gueye"},{"id":"622","name":"Cheikhou Kouyate"},{"id":"623","name":"Cheikh Ndoye"},{"id":"624","name":"Pape Alioune N'Diaye"},{"id":"625","name":"Sadio Mane"},{"id":"626","name":"Moussa Sow"},{"id":"627","name":"Moussa Konate"},{"id":"628","name":"Keita Balde"},{"id":"629","name":"M'Baye Niang"},{"id":"630","name":"Ismaila Sarr"},{"id":"631","name":"Mame Diouf"}]}`