const rawData = `[
    {
      "Trophy, Official Ball & Logos": "0 Panini Logo",
      "Stadia": "8 Ekaterinburg Arena",
      "Host cities": "20 Moscow 1",
      "Russia": "32 Team Logo - Russia",
      "Saudi Arabia": "52 Team Logo - Saudi Arabia",
      "Egypt": "72 Team Logo - Egypt",
      "Uruguay": "92 Team Logo - Uruguay",
      "Portugal": "112 Team Logo - Portugal",
      "Spain": "132 Team Logo - Spain",
      "Morocco": "152 Team Logo - Morocco",
      "Iran": "172 Team Logo - Iran",
      "France": "192 Team Logo - France",
      "Australia": "212 Team Logo - Australia",
      "Peru": "232 Team Logo - Peur",
      "Denmark": "252 Team Logo - Denmark",
      "Argentina": "272 Team Logo - Argentina",
      "Iceland": "292 Team Logo - Iceland",
      "Croatia": "312 Team Logo - Croatia",
      "Nigeria": "332 Team Logo - Nigeria",
      "Brazil": "352 Team Logo - Brazil",
      "Switzerland": "372 Team Logo - Switzerland",
      "Costa Rica": "392 Team Logo - Costa Rica",
      "Serbia": "412 Team Logo - Serbia",
      "Germany": "432 Team Logo - Germany",
      "Mexico": "452 Team Logo - Mexico",
      "Sweden": "472 Team Logo - Sweden",
      "South Korea": "492 Team Logo - South Korea",
      "Belgium": "512 Team Logo - Belgium",
      "Panama": "532 Team Logo - Panama",
      "Tunisia": "552 Team Logo - Tunisia",
      "England": "572 Team Logo - England",
      "Poland": "592 Team Logo - Poland",
      "Senegal": "612 Team Logo - Senegal"
    },
    {
      "Trophy, Official Ball & Logos": "1 FIFA Logo",
      "Stadia": "9 Kaliningrad Stadium",
      "Host cities": "21 Moscow 2",
      "Russia": "33 Team Photo - Russia",
      "Saudi Arabia": "53 Team Photo - Saudi Arabia",
      "Egypt": "73 Team Photo - Egypt",
      "Uruguay": "93 Team Photo - Uruguay",
      "Portugal": "113 Team Photo - Portugal",
      "Spain": "133 Team Photo - Spain",
      "Morocco": "153 Team Photo - Morocco",
      "Iran": "173 Team Photo - Iran",
      "France": "193 Team Photo - France",
      "Australia": "213 Team Photo - Australia",
      "Peru": "233 Team Photo - Peru",
      "Denmark": "253 Team Photo - Denmark",
      "Argentina": "273 Team Photo - Argentina",
      "Iceland": "293 Team Photo - Iceland",
      "Croatia": "313 Team Photo - Croatia",
      "Nigeria": "333 Team Photo - Nigeria",
      "Brazil": "353 Team Photo - Brazil",
      "Switzerland": "373 Team Photo - Switzerland",
      "Costa Rica": "393 Team Photo - Costa Rica",
      "Serbia": "413 Team Photo - Serbia",
      "Germany": "433 Team Photo - Germany",
      "Mexico": "453 Team Photo - Mexico",
      "Sweden": "473 Team Photo - Sweden",
      "South Korea": "493 Team Photo - South Korea",
      "Belgium": "513 Team Photo - Belgium",
      "Panama": "533 Team Photo - Panama",
      "Tunisia": "553 Team Photo - Tunisia",
      "England": "573 Team Photo - England",
      "Poland": "593 Team Photo - Poland",
      "Senegal": "613 Team Photo - Senegal"
    },
    {
      "Trophy, Official Ball & Logos": "2 World Cup Trophy",
      "Stadia": "10 Kazan Arena",
      "Host cities": "22 Kaliningrad",
      "Russia": "34 Igor Akinfeev",
      "Saudi Arabia": "54 Abdullah Al-Mayouf",
      "Egypt": "74 Essam El Hadary",
      "Uruguay": "94 Fernando Muslera",
      "Portugal": "114 Rui Patricio",
      "Spain": "134 David de Gea",
      "Morocco": "154 Munir Mohamedi",
      "Iran": "174 Alireza Beiranvand",
      "France": "194 Hugo Lloris",
      "Australia": "214 Mathew Ryan",
      "Peru": "234 Pedro Gallese",
      "Denmark": "254 Kasper Schmeichel",
      "Argentina": "274 Sergio Romero",
      "Iceland": "294 Hannes Halldorsson",
      "Croatia": "314 Danijel Subasic",
      "Nigeria": "334 Ikechukwu Ezenwa",
      "Brazil": "354 Alisson",
      "Switzerland": "374 Yann Sommer",
      "Costa Rica": "394 Keylor Navas",
      "Serbia": "414 Vladimir Stojkovic",
      "Germany": "434 Manuel Neuer",
      "Mexico": "454 Guillermo Ochoa",
      "Sweden": "474 Robin Olsen",
      "South Korea": "494 Kim Seung-gyu",
      "Belgium": "514 Thibaut Courtois",
      "Panama": "534 Jaime Penedo",
      "Tunisia": "554 Aymen Mathlouthi",
      "England": "574 Joe Hart",
      "Poland": "594 Lukasz Fabianski",
      "Senegal": "614 Khadim N'Diaye"
    },
    {
      "Trophy, Official Ball & Logos": "3 2018 World Cup Graphic 1",
      "Stadia": "11 Spartak Stadium",
      "Host cities": "23 Saint Petersburg",
      "Russia": "35 Igor Smolnikov",
      "Saudi Arabia": "55 Osama Hawsawi",
      "Egypt": "75 Ali Gabr",
      "Uruguay": "95 Maxi Pereira",
      "Portugal": "115 Bruno Alves",
      "Spain": "135 Jordi Alba",
      "Morocco": "155 Medhi Benatia",
      "Iran": "175 Pejman Montazeri",
      "France": "195 Raphael Varane",
      "Australia": "215 Mitchell Langerak",
      "Peru": "235 Carlos Caceda",
      "Denmark": "255 Jannik Vestergaard",
      "Argentina": "275 Gabriel Mercado",
      "Iceland": "295 Birkir Saevarsson",
      "Croatia": "315 Sime Vrsaljko",
      "Nigeria": "335 Elderson Echiejile",
      "Brazil": "355 Dani Alves",
      "Switzerland": "375 Stephan Lichtsteiner",
      "Costa Rica": "395 Giancarlo Gonzalez",
      "Serbia": "415 Branislav Ivanovic",
      "Germany": "435 Mats Hummels",
      "Mexico": "455 Hugo Ayala",
      "Sweden": "475 Mikael Lustig",
      "South Korea": "495 Kim Young-gwon",
      "Belgium": "515 Toby Alderweireld",
      "Panama": "535 Jose Calderon",
      "Tunisia": "555 Ali Maaloul",
      "England": "575 Jordan Pickford",
      "Poland": "595 Wojciech Szczesny",
      "Senegal": "615 Kara Mbodji"
    },
    {
      "Trophy, Official Ball & Logos": "4 2018 World Cup Graphic 2",
      "Stadia": "12 Nizhny Novgorod Stadium",
      "Host cities": "24 Sochi",
      "Russia": "36 Viktor Vasin",
      "Saudi Arabia": "56 Abdullah Al-Zori",
      "Egypt": "76 Ahmed El Mohamady",
      "Uruguay": "96 Diego Godin",
      "Portugal": "116 Pepe",
      "Spain": "136 Nacho",
      "Morocco": "156 Nabil Dirar",
      "Iran": "176 Vouria Ghafouri",
      "France": "196 Lucas Digne",
      "Australia": "216 Milos Degenek",
      "Peru": "236 Aldo Corzo",
      "Denmark": "256 Simon Kjaer",
      "Argentina": "276 Federico Fazio",
      "Iceland": "296 Ragnar Sigurosson",
      "Croatia": "316 Ivan Strinic",
      "Nigeria": "336 Shehu Abdullahi",
      "Brazil": "356 Thiago Silva",
      "Switzerland": "376 Manuel Akanji",
      "Costa Rica": "396 Cristian Gamboa",
      "Serbia": "416 Aleksandar Kolarov",
      "Germany": "436 Antonio Rudiger",
      "Mexico": "456 Diego Reyes",
      "Sweden": "476 Victor Nilsson Lindelof",
      "South Korea": "496 Kim Jin-su",
      "Belgium": "516 Thomas Vermaelen",
      "Panama": "536 Michael Murillo",
      "Tunisia": "556 Syam Ben Youssef",
      "England": "576 Gary Cahill",
      "Poland": "596 Lukasz Piszczek",
      "Senegal": "616 Lamine Gassama"
    },
    {
      "Trophy, Official Ball & Logos": "5 2018 World Cup Logo 1",
      "Stadia": "13 Luzhniki Stadium",
      "Host cities": "25 Rostov-on-Don",
      "Russia": "37 Mario Fernandes",
      "Saudi Arabia": "57 Mansoor Al-Harbi",
      "Egypt": "77 Omar Gaber",
      "Uruguay": "97 Martin Caceres",
      "Portugal": "117 Jose Fonte",
      "Spain": "137 Nacho Monreal",
      "Morocco": "157 Romain Saiss",
      "Iran": "177 Jalal Hosseini",
      "France": "197 Djibril Sidibe",
      "Australia": "217 Bailey Wright",
      "Peru": "237 Miguel Trauco",
      "Denmark": "257 Andreas Christensen",
      "Argentina": "277 Javier Mascherano",
      "Iceland": "297 Kari Arnason",
      "Croatia": "317 Dejan Lovren",
      "Nigeria": "337 William Troost-Ekong",
      "Brazil": "357 Miranda",
      "Switzerland": "377 Michael Lang",
      "Costa Rica": "397 Bryan Oviedo",
      "Serbia": "417 Antonio Rukavina",
      "Germany": "437 Jerome Boateng",
      "Mexico": "457 Hector Moreno",
      "Sweden": "478 Andreas Granqvist",
      "South Korea": "497 Kwak Tae-hwi",
      "Belgium": "517 Jan Vertonghen",
      "Panama": "537 Fidel Escobar",
      "Tunisia": "557 Aymen Abdennour",
      "England": "577 Kyle Walker",
      "Poland": "597 Kamil Glik",
      "Senegal": "617 Kalidou Koulibaly"
    },
    {
      "Trophy, Official Ball & Logos": "6 2018 World Cup Logo 2",
      "Stadia": "14 Rostov Arena",
      "Host cities": "26 Volgograd",
      "Russia": "38 Fedor Kudryashov",
      "Saudi Arabia": "58 Omar Hawsawi",
      "Egypt": "78 Ramy Rabia",
      "Uruguay": "98 Jose Gimenez",
      "Portugal": "118 Eliseu",
      "Spain": "138 Gerard Pique",
      "Morocco": "158 Fouad Chafik",
      "Iran": "178 Milad Mohammadi",
      "France": "198 Samuel Umtiti",
      "Australia": "218 Aziz Behich",
      "Peru": "238 Christian Ramos",
      "Denmark": "258 Andreas Bjelland",
      "Argentina": "278 Nicolas Otamendi",
      "Iceland": "298 Ari Skulason",
      "Croatia": "318 Domagoj Vida",
      "Nigeria": "338 Leon Balogun",
      "Brazil": "358 Filipe Luis",
      "Switzerland": "378 Ricardo Rodriguez",
      "Costa Rica": "398 Francisco Calvo",
      "Serbia": "418 Matija Nastasic",
      "Germany": "438 Joshua Kimmich",
      "Mexico": "458 Jesus Gallardo",
      "Sweden": "478 Martin Olsson",
      "South Korea": "498 Hong Jeong-ho",
      "Belgium": "518 Vincent Kompany",
      "Panama": "538 Roman Torres",
      "Tunisia": "558 Hamdi Nagguez",
      "England": "578 John Stones",
      "Poland": "598 Michal Pazdan",
      "Senegal": "618 Salif Sane"
    },
    {
      "Trophy, Official Ball & Logos": "7 Official Ball",
      "Stadia": "15 Saint Petersburg Stadium",
      "Host cities": "27 Kazan",
      "Russia": "39 Ilya Kutepov",
      "Saudi Arabia": "59 Yasser Al-Shahrani",
      "Egypt": "79 Ahmed Hegazi",
      "Uruguay": "99 Sebastian Coates",
      "Portugal": "119 Cedric",
      "Spain": "139 Sergio Ramos",
      "Morocco": "159 Hamza Mendyl",
      "Iran": "179 Morteza Pouraliganji",
      "France": "199 Layvin Kurzawa",
      "Australia": "219 Trent Sainsbury",
      "Peru": "239 Luis Advincula",
      "Denmark": "259 Mathias Jorgensen",
      "Argentina": "279 Marcos Rojo",
      "Iceland": "299 Sverrir Ingason",
      "Croatia": "319 Josip Pivaric",
      "Nigeria": "339 Kenneth Omeruo",
      "Brazil": "359 Marquinhos",
      "Switzerland": "379 Johan Djourou",
      "Costa Rica": "399 Kendall Waston",
      "Serbia": "419 Dusko Tosic",
      "Germany": "439 Jonas Hector",
      "Mexico": "459 Miguel Layun",
      "Sweden": "479 Ludwig Augustinsson",
      "South Korea": "499 Jang Hyun-soo",
      "Belgium": "519 Thomas Meunier",
      "Panama": "539 Adolfo Machado",
      "Tunisia": "559 Yassine Meriah",
      "England": "579 Ryan Bertrand",
      "Poland": "599 Thiago Cionek",
      "Senegal": "619 Saliou Ciss"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "16 Samara Arena",
      "Host cities": "28 Nizhny Novgorod",
      "Russia": "40 Dmitri Kombarov",
      "Saudi Arabia": "60 Motaz Hawsawi",
      "Egypt": "80 Ahmed Abdelmonem Fathy",
      "Uruguay": "100 Gaston Silva",
      "Portugal": "120 Raphael Guerreiro",
      "Spain": "140 Daniel Carvajal",
      "Morocco": "160 Achraf Hakimi",
      "Iran": "180 Ramin Rezaeian",
      "France": "200 Laurent Koscielny",
      "Australia": "220 Ryan McGowan",
      "Peru": "240 Alberto Rodriguez",
      "Denmark": "260 Jens Stryger Larsen",
      "Argentina": "280 Ramiro Funes Mori",
      "Iceland": "300 Hordur Magnusson",
      "Croatia": "320 Vedran Corluka",
      "Nigeria": "340 Ola Aina",
      "Brazil": "360 Marcelo",
      "Switzerland": "380 Fabian Schar",
      "Costa Rica": "400 Ronald Matarrita",
      "Serbia": "420 Nikola Maksimovic",
      "Germany": "440 Julian Draxler",
      "Mexico": "460 Carlos Salcedo",
      "Sweden": "480 Emil Krafth",
      "South Korea": "500 Koo Ja-cheol",
      "Belgium": "520 Axel Witsel",
      "Panama": "540 Eric Davis",
      "Tunisia": "560 Oussama Haddadi",
      "England": "580 Danny Rose",
      "Poland": "600 Bartosz Bereszynski",
      "Senegal": "620 Moussa Wague"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "17 Mordovia Arena",
      "Host cities": "29 Samara",
      "Russia": "41 Aleksei Miranchuk",
      "Saudi Arabia": "61 Mohammed Al-Breik",
      "Egypt": "81 Mohamed Abdel Shafy",
      "Uruguay": "101 Mathias Corujo",
      "Portugal": "121 Joao Moutinho",
      "Spain": "141 Sergio Busquets",
      "Morocco": "161 Mbark Boussoufa",
      "Iran": "181 Ehsan Hajsafi",
      "France": "201 Blaise Matuidi",
      "Australia": "221 Mark Milligan",
      "Peru": "241 Miguel Araujo",
      "Denmark": "261 Peter Ankersen",
      "Argentina": "281 Lucas Biglia",
      "Iceland": "301 Aron Gunnarsson",
      "Croatia": "321 Ivan Rakitic",
      "Nigeria": "341 John Obi Mikel",
      "Brazil": "361 Willian",
      "Switzerland": "381 Granit Xhaka",
      "Costa Rica": "401 Michael Umana",
      "Serbia": "421 Jagos Vukovic",
      "Germany": "441 Toni Kroos",
      "Mexico": "461 Jonathan dos Santos",
      "Sweden": "481 Pontus Jansson",
      "South Korea": "501 Kwon Chang-hoon",
      "Belgium": "521 Radja Nainggolan",
      "Panama": "541 Luis Ovalle",
      "Tunisia": "561 Ferjani Sassi",
      "England": "581 Phil Jones",
      "Poland": "601 Artur Jedrzejczyk",
      "Senegal": "621 Idrissa Gueye"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "18 Fisht Stadium",
      "Host cities": "30 Yekaterinburg",
      "Russia": "42 Denis Glushakov",
      "Saudi Arabia": "62 Taisir Al-Jassim",
      "Egypt": "82 Saad Samir",
      "Uruguay": "102 Egidio Arevalo Rios",
      "Portugal": "122 Joao Mario",
      "Spain": "142 Thiago Alcantara",
      "Morocco": "162 Karim El Ahmadi",
      "Iran": "182 Omid Ebrahimi",
      "France": "202 N'Golo Kante",
      "Australia": "222 Aaron Mooy",
      "Peru": "242 Christian Cueva",
      "Denmark": "262 Riza Durmisi",
      "Argentina": "282 Enzo Perez",
      "Iceland": "302 Birkir Bjarnason",
      "Croatia": "322 Luka Modric",
      "Nigeria": "342 Ogenyi Onazi",
      "Brazil": "362 Paulinho",
      "Switzerland": "382 Steven Zuber",
      "Costa Rica": "402 Johnny Acosta",
      "Serbia": "422 Dusan Tadic",
      "Germany": "442 Emre Can",
      "Mexico": "462 Giovani dos Santos",
      "Sweden": "482 Sebastian Larsson",
      "South Korea": "502 Ki Sung-yueng",
      "Belgium": "522 Kevin De Bruyne",
      "Panama": "542 Felipe Baloy",
      "Tunisia": "562 Wahbi Khazri",
      "England": "582 Jordan Henderson",
      "Poland": "602 Maciej Rybus",
      "Senegal": "622 Cheikhou Kouyate"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "19 Volgograd Arena",
      "Host cities": "31 Saransk",
      "Russia": "43 Aleksandr Golovin",
      "Saudi Arabia": "63 Salman Al-Faraj",
      "Egypt": "83 Tarek Hamed",
      "Uruguay": "103 Alvaro Gonzalez",
      "Portugal": "123 Danilo Pereira",
      "Spain": "143 Isco",
      "Morocco": "163 Younes Belhanda",
      "Iran": "183 Saeid Ezatolahi",
      "France": "203 Thomas Lemar",
      "Australia": "223 James Troisi",
      "Peru": "243 Renato Tapia",
      "Denmark": "263 William Kvist",
      "Argentina": "283 Angel Di Maria",
      "Iceland": "303 Emil Hallfredsson",
      "Croatia": "323 Marcelo Brozovic",
      "Nigeria": "343 Etebo Oghenekaro",
      "Brazil": "363 Fernandinho",
      "Switzerland": "383 Blerim Dzemaili",
      "Costa Rica": "403 Bryan Ruiz",
      "Serbia": "423 Sergej Milinkovic-Savic",
      "Germany": "443 Leon Goretzka",
      "Mexico": "463 Andres Guardado",
      "Sweden": "483 Emil Forsberg",
      "South Korea": "503 Nam Tae-hee",
      "Belgium": "523 Marouane Fellaini",
      "Panama": "543 Gabriel Gomez",
      "Tunisia": "563 Mohamed Amine Ben Amor",
      "England": "583 Alex Oxlade-Chamberlain",
      "Poland": "603 Jakub Blaszczykowski",
      "Senegal": "623 Cheikh Ndoye"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "",
      "Host cities": "",
      "Russia": "44 Yuri Zhirkov",
      "Saudi Arabia": "64 Abdulmalek Al-Khaibri",
      "Egypt": "84 Mahmoud Kahraba",
      "Uruguay": "104 Nicolas Lodeiro",
      "Portugal": "124 William Carvalho",
      "Spain": "144 Koke",
      "Morocco": "164 Nordin Amrabat",
      "Iran": "184 Vahid Amiri",
      "France": "204 Adrien Rabiot",
      "Australia": "224 Mile Jedinak",
      "Peru": "244 Andy Polo",
      "Denmark": "264 Thomas Delaney",
      "Argentina": "284 Marcos Acuna",
      "Iceland": "304 Gylfi Sigurdsson",
      "Croatia": "324 Marko Rog",
      "Nigeria": "344 Wilfred Ndidi",
      "Brazil": "364 Casemiro",
      "Switzerland": "384 Denis Zakaria",
      "Costa Rica": "404 Celso Borges",
      "Serbia": "424 Nemanja Matic",
      "Germany": "444 Julian Brandt",
      "Mexico": "464 Hector Herrera",
      "Sweden": "484 Gustav Svensson",
      "South Korea": "504 Han Kook-young",
      "Belgium": "524 Youri Tielemans",
      "Panama": "544 Edgar Barcenas",
      "Tunisia": "564 Ghailene Chaalali",
      "England": "584 Dele Alli",
      "Poland": "604 Kamil Grosicki",
      "Senegal": "624 Pape Alioune N'Diaye"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "",
      "Host cities": "",
      "Russia": "45 Aleksandr Samedov",
      "Saudi Arabia": "65 Salman Al-Moasher",
      "Egypt": "85 Mohamed Elneny",
      "Uruguay": "105 Carlos Sanchez",
      "Portugal": "125 Andre Gomes",
      "Spain": "145 Marco Asensio",
      "Morocco": "165 Faycal Fajr",
      "Iran": "185 Alireza Jahanbakhsh",
      "France": "205 Paul Pogba",
      "Australia": "225 Massimo Luongo",
      "Peru": "245 Yoshimar Yotun",
      "Denmark": "265 Christian Eriksen",
      "Argentina": "285 Ever Banega",
      "Iceland": "305 Arnor Ingvi Traustason",
      "Croatia": "325 Mario Pasalic",
      "Nigeria": "345 Mikel Agu",
      "Brazil": "365 Renato Augusto",
      "Switzerland": "385 Xherdan Shaqiri",
      "Costa Rica": "405 Christian Bolanos",
      "Serbia": "425 Luka Milivojevic",
      "Germany": "445 Sebastian Rudy",
      "Mexico": "465 Javier Aquino",
      "Sweden": "485 Viktor Claesson",
      "South Korea": "505 Lee Chung-yong",
      "Belgium": "525 Mousa Dembele",
      "Panama": "545 Armando Cooper",
      "Tunisia": "565 Naim Sliti",
      "England": "585 Eric Dier",
      "Poland": "605 Grzegorz Krychowiak",
      "Senegal": "625 Sadio Mane"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "",
      "Host cities": "",
      "Russia": "46 Aleksandr Erokhin",
      "Saudi Arabia": "66 Yahya Al-Shehri",
      "Egypt": "86 Mahmoud Trezeguet",
      "Uruguay": "106 Cristian Rodriguez",
      "Portugal": "126 Ricardo Quaresma",
      "Spain": "146 Andres Iniesta",
      "Morocco": "166 Hakim Ziyech",
      "Iran": "186 Ashkan Dejagah",
      "France": "206 Olivier Giroud",
      "Australia": "226 Jackson Irvine",
      "Peru": "246 Edison Flores",
      "Denmark": "266 Lasse Schone",
      "Argentina": "286 Eduardo Salvio",
      "Iceland": "306 Rurik Gislason",
      "Croatia": "326 Milan Badelj",
      "Nigeria": "346 Ahmed Musa",
      "Brazil": "366 Giuliano",
      "Switzerland": "386 Valon Behrami",
      "Costa Rica": "406 Randall Azofeifa",
      "Serbia": "426 Adem Ljajic",
      "Germany": "446 Leroy Sane",
      "Mexico": "466 Jesus Corona",
      "Sweden": "486 Jimmy Durmaz",
      "South Korea": "506 Jung Woo-young",
      "Belgium": "526 Nacer Chadli",
      "Panama": "546 Alberto Quintero",
      "Tunisia": "566 Youssef Msakni",
      "England": "586 Adam Lallana",
      "Poland": "606 Krzysztof Maczynski",
      "Senegal": "626 Moussa Sow"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "",
      "Host cities": "",
      "Russia": "47 Alan Dzagoev",
      "Saudi Arabia": "67 Salem Al-Dawsari",
      "Egypt": "87 Abdallah Said",
      "Uruguay": "107 Matias Vecino",
      "Portugal": "127 Bernardo Silva",
      "Spain": "147 David Villa",
      "Morocco": "167 Youssef Ait Bennasser",
      "Iran": "187 Saman Ghoddos",
      "France": "207 Antoine Griezmann",
      "Australia": "227 Tom Rogic",
      "Peru": "247 Paolo Hurtado",
      "Denmark": "267 Pione Sisto",
      "Argentina": "287 Mauro Icardi",
      "Iceland": "307 Johann Gudmundsson",
      "Croatia": "327 Mateo Kovacic",
      "Nigeria": "347 Victor Moses",
      "Brazil": "367 Philippe Coutinho",
      "Switzerland": "387 Gelson Fernandes",
      "Costa Rica": "407 David Guzman",
      "Serbia": "427 Nemanja Gudelj",
      "Germany": "447 Mesut Ozil",
      "Mexico": "467 Hirving Lozano",
      "Sweden": "487 Albin Ekdal",
      "South Korea": "507 Lee Jae-sung",
      "Belgium": "527 Eden Hazard",
      "Panama": "547 Anibal Godoy",
      "Tunisia": "567 Fakhreddine Ben Youssef",
      "England": "587 Jesse Lingard",
      "Poland": "607 Piotr Zielinski",
      "Senegal": "627 Moussa Konate"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "",
      "Host cities": "",
      "Russia": "48 Daler Kuzyayev",
      "Saudi Arabia": "68 Nawaf Al-Abed",
      "Egypt": "88 Ramadan Sobhi",
      "Uruguay": "108 Edinson Cavani",
      "Portugal": "128 Andre Silva",
      "Spain": "148 Saul Niguez",
      "Morocco": "168 Khalid Boutaib",
      "Iran": "188 Mehdi Taremi",
      "France": "208 Alexandre Lacazette",
      "Australia": "228 Tim Cahill",
      "Peru": "248 Paolo Guerrero",
      "Denmark": "268 Nicklas Bendtner",
      "Argentina": "288 Lionel Messi",
      "Iceland": "308 Alfred Finnbogason",
      "Croatia": "328 Andrej Kramaric",
      "Nigeria": "348 Moses Simon",
      "Brazil": "368 Douglas Costa",
      "Switzerland": "388 Breel Embolo",
      "Costa Rica": "408 Rodney Wallace",
      "Serbia": "428 Mijat Gacinovic",
      "Germany": "448 Sami Khedira",
      "Mexico": "468 Raul Jimenez",
      "Sweden": "488 Isaac Kiese Thelin",
      "South Korea": "508 Son Heung-min",
      "Belgium": "528 Yannick Carrasco",
      "Panama": "548 Blas Perez",
      "Tunisia": "568 Taha Yassine Khenissi",
      "England": "588 Raheem Sterling",
      "Poland": "608 Karol Linetty",
      "Senegal": "628 Keita Balde"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "",
      "Host cities": "",
      "Russia": "49 Dmitry Poloz",
      "Saudi Arabia": "69 Mohammad Al-Sahlawi",
      "Egypt": "89 Ahmed Hassan",
      "Uruguay": "109 Luis Suarez",
      "Portugal": "129 Gelson Martins",
      "Spain": "149 Alvaro Morata",
      "Morocco": "169 Rachid Alioui",
      "Iran": "189 Karim Ansarifard",
      "France": "209 Kylian Mbappe",
      "Australia": "229 Mathew Leckie",
      "Peru": "249 Jefferson Farfan",
      "Denmark": "269 Nicolai Jorgensen",
      "Argentina": "289 Paulo Dybala",
      "Iceland": "309 Jon Dadi Bodvarsson",
      "Croatia": "329 Nikola Kalinic",
      "Nigeria": "349 Odion Ighalo",
      "Brazil": "369 Roberto Firmino",
      "Switzerland": "389 Haris Seferovic",
      "Costa Rica": "409 Joel Campbell",
      "Serbia": "429 Filip Kostic",
      "Germany": "449 Mario Gotze",
      "Mexico": "469 Carlos Vela",
      "Sweden": "489 Marcus Berg",
      "South Korea": "509 Ji Dong-won",
      "Belgium": "529 Dries Mertens",
      "Panama": "549 Gabriel Torres",
      "Tunisia": "569 Yoann Touzghar",
      "England": "589 Harry Kane",
      "Poland": "609 Robert Lewandowski",
      "Senegal": "629 M'Baye Niang"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "",
      "Host cities": "",
      "Russia": "50 Fedor Smolov",
      "Saudi Arabia": "70 Nasser Al-Shamrani",
      "Egypt": "90 Mohamed Salah",
      "Uruguay": "110 Cristhian Stuani",
      "Portugal": "130 Cristiano Ronaldo",
      "Spain": "150 Vitolo",
      "Morocco": "170 Aziz Bouhaddouz",
      "Iran": "190 Reza Ghoochannejhad",
      "France": "210 Ousmane Dembele",
      "Australia": "230 Tomi Juric",
      "Peru": "250 Raul Ruidiaz",
      "Denmark": "270 Yussuf Poulsen",
      "Argentina": "290 Sergio Aguero",
      "Iceland": "310 Vidar Orn Kjartansson",
      "Croatia": "330 Mario Mandzukic",
      "Nigeria": "350 Alex Iwobi",
      "Brazil": "370 Gabriel Jesus",
      "Switzerland": "390 Admir Mehmedi",
      "Costa Rica": "410 Marco Urena",
      "Serbia": "430 Aleksandar Mitrovic",
      "Germany": "450 Thomas Muller",
      "Mexico": "470 Javier Hernandez",
      "Sweden": "490 John Guidetti",
      "South Korea": "510 Kim Shin-wook",
      "Belgium": "530 Michy Batshuayi",
      "Panama": "550 Luis Tejada",
      "Tunisia": "570 Anice Badri",
      "England": "590 Marcus Rashford",
      "Poland": "610 Lukasz Teodorczyk",
      "Senegal": "630 Ismaila Sarr"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "",
      "Host cities": "",
      "Russia": "51 Aleksandr Kokorin",
      "Saudi Arabia": "71 Fahad Al-Muwallad",
      "Egypt": "91 Amr Gamal",
      "Uruguay": "111 Diego Rolan",
      "Portugal": "131 Nani",
      "Spain": "151 Diego Costa",
      "Morocco": "171 Youssef En-Nesyri",
      "Iran": "191 Sardar Azmoun",
      "France": "211 Anthony Martial",
      "Australia": "231 Robbie Kruse",
      "Peru": "251 Andre Carrillo",
      "Denmark": "271 Andreas Cornelius",
      "Argentina": "291 Gonzalo Higuain",
      "Iceland": "311 Bjorn Sigurdarson",
      "Croatia": "331 Ivan Perisic",
      "Nigeria": "351 Kelechi Iheanacho",
      "Brazil": "371 Neymar Jr",
      "Switzerland": "391 Eren Derdiyok",
      "Costa Rica": "411 Johan Venegas",
      "Serbia": "431 Aleksandar Prijovic",
      "Germany": "451 Timo Werner",
      "Mexico": "471 Oribe Peralta",
      "Sweden": "491 Ola Toivonen",
      "South Korea": "511 Hwang Hee-chan",
      "Belgium": "531 Romelu Lukaku",
      "Panama": "551 Abdiel Arroyo",
      "Tunisia": "571 Ahmed Akaichi",
      "England": "591 Jamie Vardy",
      "Poland": "611 Arkadiusz Milik",
      "Senegal": "631 Mame Diouf"
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "",
      "Host cities": "",
      "Russia": "",
      "Saudi Arabia": "",
      "Egypt": "",
      "Uruguay": "",
      "Portugal": "",
      "Spain": "",
      "Morocco": "",
      "Iran": "",
      "France": "",
      "Australia": "",
      "Peru": "",
      "Denmark": "",
      "Argentina": "",
      "Iceland": "",
      "Croatia": "",
      "Nigeria": "",
      "Brazil": "",
      "Switzerland": "",
      "Costa Rica": "",
      "Serbia": "",
      "Germany": "",
      "Mexico": "",
      "Sweden": "",
      "South Korea": "",
      "Belgium": "",
      "Panama": "",
      "Tunisia": "",
      "England": "",
      "Poland": "",
      "Senegal": ""
    },
    {
      "Trophy, Official Ball & Logos": "",
      "Stadia": "",
      "Host cities": "",
      "Russia": "",
      "Saudi Arabia": "",
      "Egypt": "",
      "Uruguay": "",
      "Portugal": "",
      "Spain": "",
      "Morocco": "",
      "Iran": "",
      "France": "",
      "Australia": "",
      "Peru": "",
      "Denmark": "",
      "Argentina": "",
      "Iceland": "",
      "Croatia": "",
      "Nigeria": "",
      "Brazil": "",
      "Switzerland": "",
      "Costa Rica": "",
      "Serbia": "",
      "Germany": "",
      "Mexico": "",
      "Sweden": "",
      "South Korea": "",
      "Belgium": "",
      "Panama": "",
      "Tunisia": "",
      "England": "",
      "Poland": "",
      "Senegal": ""
    }
  ]`;


const jsonData = JSON.parse(rawData);
const formattedData = {};

jsonData.forEach(group => {
    for (let key in group) {
        formattedData[key] = formattedData[String(key)] || [];
        if (group[key]) {
            const item = group[key].split(' ');
            formattedData[key].push({
                id: item.shift(), // takes away 1st element
                name: item.join(' ')
            });
            
            // console.log(item)
        }
    } 
});

console.log(JSON.stringify(formattedData))

